CREATE TABLE [XrmTds].[sys_databases] (
    [name]                                       NVARCHAR (160)   NOT NULL,
    [database_id]                                INT              NOT NULL,
    [source_database_id]                         INT              DEFAULT (NULL) NULL,
    [owner_sid]                                  VARBINARY (85)   DEFAULT (NULL) NULL,
    [create_date]                                DATETIME         NOT NULL,
    [compatibility_level]                        TINYINT          DEFAULT ((130)) NOT NULL,
    [collation_name]                             [sysname]        DEFAULT (NULL) NULL,
    [user_access]                                TINYINT          DEFAULT ((0)) NULL,
    [user_access_desc]                           NVARCHAR (60)    DEFAULT ('MULTI_USER') NULL,
    [is_read_only]                               BIT              DEFAULT ((1)) NULL,
    [is_auto_close_on]                           BIT              DEFAULT ((0)) NOT NULL,
    [is_auto_shrink_on]                          BIT              DEFAULT ((0)) NULL,
    [state]                                      TINYINT          DEFAULT ((0)) NULL,
    [state_desc]                                 NVARCHAR (60)    DEFAULT ('ONLINE') NULL,
    [is_in_standby]                              BIT              DEFAULT ((0)) NULL,
    [is_cleanly_shutdown]                        BIT              DEFAULT ((0)) NULL,
    [is_supplemental_logging_enabled]            BIT              DEFAULT ((0)) NULL,
    [snapshot_isolation_state]                   TINYINT          DEFAULT ((1)) NULL,
    [snapshot_isolation_state_desc]              NVARCHAR (60)    DEFAULT ('ON') NULL,
    [is_read_committed_snapshot_on]              BIT              DEFAULT ((1)) NULL,
    [recovery_model]                             TINYINT          DEFAULT ((1)) NULL,
    [recovery_model_desc]                        NVARCHAR (60)    DEFAULT ('FULL') NULL,
    [page_verify_option]                         TINYINT          DEFAULT ((2)) NULL,
    [page_verify_option_desc]                    NVARCHAR (60)    DEFAULT ('CHECKSUM') NULL,
    [is_auto_create_stats_on]                    BIT              DEFAULT ((0)) NULL,
    [is_auto_create_stats_incremental_on]        BIT              DEFAULT ((0)) NULL,
    [is_auto_update_stats_on]                    BIT              DEFAULT ((0)) NULL,
    [is_auto_update_stats_async_on]              BIT              DEFAULT ((0)) NULL,
    [is_ansi_null_default_on]                    BIT              DEFAULT ((0)) NULL,
    [is_ansi_nulls_on]                           BIT              DEFAULT ((0)) NULL,
    [is_ansi_padding_on]                         BIT              DEFAULT ((0)) NULL,
    [is_ansi_warnings_on]                        BIT              DEFAULT ((0)) NULL,
    [is_arithabort_on]                           BIT              DEFAULT ((0)) NULL,
    [is_concat_null_yields_null_on]              BIT              DEFAULT ((0)) NULL,
    [is_numeric_roundabort_on]                   BIT              DEFAULT ((0)) NULL,
    [is_quoted_identifier_on]                    BIT              DEFAULT ((0)) NULL,
    [is_recursive_triggers_on]                   BIT              DEFAULT ((0)) NULL,
    [is_cursor_close_on_commit_on]               BIT              DEFAULT ((0)) NULL,
    [is_local_cursor_default]                    BIT              DEFAULT ((0)) NULL,
    [is_fulltext_enabled]                        BIT              DEFAULT ((0)) NULL,
    [is_trustworthy_on]                          BIT              DEFAULT ((0)) NULL,
    [is_db_chaining_on]                          BIT              DEFAULT ((0)) NULL,
    [is_parameterization_forced]                 BIT              DEFAULT ((0)) NULL,
    [is_master_key_encrypted_by_server]          BIT              DEFAULT ((0)) NOT NULL,
    [is_query_store_on]                          BIT              DEFAULT ((0)) NULL,
    [is_published]                               BIT              DEFAULT ((0)) NOT NULL,
    [is_subscribed]                              BIT              DEFAULT ((0)) NOT NULL,
    [is_merge_published]                         BIT              DEFAULT ((0)) NOT NULL,
    [is_distributor]                             BIT              DEFAULT ((0)) NOT NULL,
    [is_sync_with_backup]                        BIT              DEFAULT ((0)) NOT NULL,
    [service_broker_guid]                        UNIQUEIDENTIFIER DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [is_broker_enabled]                          BIT              DEFAULT ((0)) NOT NULL,
    [log_reuse_wait]                             TINYINT          DEFAULT ((0)) NULL,
    [log_reuse_wait_desc]                        NVARCHAR (60)    DEFAULT ('NOTHING') NULL,
    [is_date_correlation_on]                     BIT              DEFAULT ((0)) NOT NULL,
    [is_cdc_enabled]                             BIT              DEFAULT ((0)) NOT NULL,
    [is_encrypted]                               BIT              DEFAULT ((0)) NULL,
    [is_honor_broker_priority_on]                BIT              DEFAULT ((0)) NULL,
    [replica_id]                                 UNIQUEIDENTIFIER DEFAULT (NULL) NULL,
    [group_database_id]                          UNIQUEIDENTIFIER DEFAULT (NULL) NULL,
    [resource_pool_id]                           INT              DEFAULT (NULL) NULL,
    [default_language_lcid]                      SMALLINT         DEFAULT (NULL) NULL,
    [default_language_name]                      NVARCHAR (128)   DEFAULT (NULL) NULL,
    [default_fulltext_language_lcid]             INT              DEFAULT (NULL) NULL,
    [default_fulltext_language_name]             NVARCHAR (128)   DEFAULT (NULL) NULL,
    [is_nested_triggers_on]                      BIT              DEFAULT (NULL) NULL,
    [is_transform_noise_words_on]                BIT              DEFAULT (NULL) NULL,
    [two_digit_year_cutoff]                      SMALLINT         DEFAULT (NULL) NULL,
    [containment]                                TINYINT          DEFAULT ((0)) NULL,
    [containment_desc]                           NVARCHAR (60)    DEFAULT ('NONE') NULL,
    [target_recovery_time_in_seconds]            INT              DEFAULT ((120)) NULL,
    [delayed_durability]                         INT              DEFAULT ((0)) NULL,
    [delayed_durability_desc]                    NVARCHAR (60)    DEFAULT ('DISABLED') NULL,
    [is_memory_optimized_elevate_to_snapshot_on] BIT              DEFAULT ((0)) NULL,
    [is_federation_member]                       BIT              DEFAULT ((0)) NULL,
    [is_remote_data_archive_enabled]             BIT              DEFAULT ((0)) NULL,
    [is_mixed_page_allocation_on]                BIT              DEFAULT ((0)) NULL,
    CONSTRAINT [cndx_PrimaryKey_sys_databases] PRIMARY KEY CLUSTERED ([database_id] ASC)
);


GO
GRANT SELECT
    ON OBJECT::[XrmTds].[sys_databases] TO [CRMReaderRole]
    AS [dbo];

