var RESOURCES={
	"MailApp_Module_Notification_Update_In_Progress": "Värskendamine on pooleli.",
	"MailApp_Module_Column_Show_Tooltip": "Veeru kuvamiseks valige veeru kõrval olev märkeruut. Veeru peitmiseks tühjendage märkeruut.",
	"MailApp_Module_Link_Title": "Linkimine",
	"MailApp_Module_Alert_Link_Batch_Message": "Lingime kontodega mitu kontakti. Selleks kulub mõni minut.",
	"PickList_KBTemplateEditor_Selector_Style_Title": "Pealkiri",
	"MoCA_OWA_App_Long_Description": "Muutke Dynamics 365 lõbusaks! Kombineerige Microsoft Dynamics 365 võimsus Outlooki paindlikkuse ja kasutusmugavusega.\nSelle meilirakendusega saate teha järgmist.\n[#LI]5D;Otsida Dynamics 365 kirjeid teile meile saatnud kontakti või müügivihje kohta[/#LI]5D;\n[#LI]5D;Lisada inimesi, kes on saatnud teile meile Dynamics 365 kontakti või müügivihjena[/#LI]5D;\n[#LI]5D;Jälgida meile seoses olemasolevate Dynamics 365 kirjetega[/#LI]5D;\n[#LI]5D;Luua isegi uusi kirjeid, mille juurde saate meile jälgida[/#LI]5D;\nÄrge laske kirjete otsimisel ja värskendamisel oma tegevust aeglustada. Selle asemel kasutage seda Microsoft Dynamics 365 rakendust, et kõik oleks käepärast ning saaksite ühenduse olemasolul alati ja kõikjal vajalikku teavet.\nPraegu toetatakse seda rakendust ainult Outlook 2013 või uuemates versioonides või Outlook Web Appis (ainult töölauabrauserid).",
	"Error_Message_0x8005f211": "Toiming nurjus, kuna teil puudub ühendus. Looge uuesti ühendus ja proovige veel kord.",
	"Error_Message_0x8005f210": "Rakenduse lähtestamisel läks kahjuks midagi valesti. Proovige uuesti või taaskäivitage rakendus.",
	"Error_Message_0x8005f215": "Sisselogimise ajal läks midagi valesti. Proovige uuesti. Kui probleem ei lahene, pöörduge süsteemiadministraatori poole.",
	"MailApp_Module_Filter_Show_Tooltip": "Saate filtrid sisse lülitada.",
	"MailApp_Module_Tracking_Filter_All": "Kõik kontaktid",
	"MailApp_Module_Alert_Previously_Tracked_Button_Create": "Loo uus kontakt",
	"MailApp_Module_Link_Button_Link_Tooltip": "Saate linkida valitud konto valitud kontaktidega.",
	"MailApp_Module_Unlink": "Tühista linkimine",
	"MailApp_Module_Link": "Link",
	"MailApp_Module_Paging_First": "Esimene",
	"MailApp_Module_Alert_Link_Error_If_Pending_Untrack": "Te ei saa sellele kontaktile kontot määrata, sest kontakti olek on Jälgimise lõpetamine on ootel.",
	"MailApp_Module_Alert_Track_Single_Error_If_Pending_Untracked": "Te ei saa seda kontakti jälgida, sest me kuvame kontakti olekuks Jälgimise lõpetamine on ootel.",
	"MailApp_Module_Column_Full_Name": "Nimi",
	"Error_Message_0x80061204": "Selle Dynamics 365 organisatsiooni puhul pole juurdepääs rakendusele lubatud. Rakendusele juurdepääsu lubamiseks võtke ühendust süsteemiadministraatoriga.",
	"MoCA_OWA_App_Longer": "Ühenduse loomiseks kulub kauem aega kui tavaliselt. Me tegeleme sellega alles.",
	"MailApp_Module_Link_Refresh_Title": "Konto värskendamise link",
	"Error_Message_0x8004a104": "Kahjuks ei saanud teie Microsoft Dynamics 365 organisatsiooniga ühendust, sest see on praegu keelatud. Proovige hiljem uuesti.",
	"Error_Message_0x80044160": "Teil puudub õigus selle organisatsiooni andmete vaatamiseks, redigeerimiseks või kustutamiseks. Võtke abi saamiseks ühendust oma administraatoriga.",
	"MailApp_Module_Refresh_Tooltip": "Saate värskendada andmeid.",
	"MailApp_Module_Alert_Untrack_Button_Delete": "Lõpeta jälgimine ja kustuta",
	"MailApp_Module_Link_Refresh_Button_Cancel": "Tühista",
	"MailApp_Module_Track": "Jälgi",
	"MailApp_Module_Column_Given_Name": "Eesnimi",
	"Brand_CRM": "Microsoft Dynamics 365",
	"MailApp_Module_Dymamics_365_Contacts": "Dynamics 365 kontaktid",
	"MailApp_Module_Link_Button_New": "Uus",
	"MailApp_Module_Alert_Untrack_Single_Error_If_Pending_Untracked": "Te ei saa selle kontakti jälgimist lõpetada, sest kontakti olek on Jälgimise lõpetamine on ootel.",
	"MailApp_Module_Column_Office_Location": "Kontori asukoht",
	"MailApp_Module_Email_Tooltip": "Saate saata meili.",
	"MailApp_Module_No_Contacts": "Ühtegi kontakti ei leitud.",
	"MoCA_OWA_Client_Download_Customizations_Message": "Kohanduste allalaadimine …",
	"MailApp_Module_Column_Email": "Meil",
	"Error_Message_0x80061210_Title": "Kas teil on sisselogimisega probleeme?",
	"MailApp_Module_Select_Untrack_Alert": "Jälgimise lõpetamiseks valige vähemalt üks kontakt.",
	"MailApp_Module_Alert_Link_Batch_Warning": "Mõningaid valitud kontakte praegu ei jälgita. Kui jätkate, hakatakse neid kontakte jälgima ja neile kontaktidele määratakse konto.",
	"MailApp_Module_Search": "Otsing",
	"Error_Message_0x80061203": "Teil on Microsoft Dynamics 365-le ainult administraatoriõigustega juurdepääs. Rakenduse kasutamiseks peab teil olema lugemis- ja kirjutuspääs.",
	"MailApp_Module_Dymamics_365_Untrack_Alert": "Te ei saa kontaktide jälgimist Dynamics CRM-i kontaktide vahekaardilt lõpetada. Kasutage kontaktide jälgimise lõpetamiseks Outlooki kontaktide vahekaarti.",
	"MoCA_OWA_Generic_Error_Title": "Vabandame",
	"Error_Message_Generic_Mobile_Client": "Midagi läks kahjuks valesti. Proovige uuesti või taaskäivitage rakendus.\nTõrkekood: ",
	"MailApp_Module_Alert_Link_Batch_Dont_Show": "Ära seda teadet enam kuva.",
	"MoCA_OWA_Org_Discovery_Loading_Message": "Organisatsiooni otsimine …",
	"MailApp_Module_Tracking_Filter_Untracked": "Mittejälgitavad kontaktid",
	"DelveActionHub.TrackingStatus": "Jälgimine",
	"MailApp_Module_Select_Email_Alert": "Meili saatmiseks valige vähemalt üks kontakt.",
	"MoCA_OWA_No_Upcoming_Activities": "Tulevased tegevused puuduvad.",
	"MoCA_OWA_Help_Link_Text": "Aidake mul see probleem lahendada",
	"MailApp_Module_Alert_Untrack_Failure_Message": "Kontakti jälgimise lõpetamine ebaõnnestus. Proovige uuesti.",
	"MailApp_Module_Alert_Untrack_Batch_Warning_If_Not_Tracked": "Mõningaid valitud kontakte ei jälgita või jälgimine on ootel. Jälgimine lõpetatakse ainult jälgitavate kontaktide puhul.",
	"MailApp_Module_Column_Title": "Tiitel",
	"MailApp_Module_Alert_Untrack_Button_Keep": "Lõpeta jälgimine ja hoia alles",
	"MailApp_Module_Alert_Previously_Tracked": "Seda kontakti jälgiti varem teenuses Dynamics CRM. Kas soovite linkida kontakti varem jälgitud kontaktiga või luua uue kontakti?",
	"MailApp_Module_Next": "Edasi",
	"MoCA_OWA_App_FirstTime": "See on esimene kord, kui teie organisatsioon seda rakendust laadib. Oodake, kuni me kõik valmis seame.",
	"MailApp_Module_Alert_Track_Single_Error_If_Pending_Tracked": "Te ei saa seda kontakti jälgida, sest me kuvame kontakti olekuks Jälgimine on ootel.",
	"MailApp_Module_Alert_Task_Error": "Saate seostuva määrata korraga ainult ühele kontaktile.",
	"MoCA_OWA_Last_Activity_Label": "Viimane tegevus",
	"MailApp_Module_Alert_Previously_Tracked_Button_Link": "Lingi",
	"MoCA_OWA_App_Short_Description": "Microsoft Dynamics 365-s saate jälgida oma meile kõikjal ja kogu aeg.",
	"MailApp_Module_Link_Refresh_Button_Refresh": "Värskenda",
	"MailApp_Module_Pending_Untrack": "Jälgimise lõpetamine on ootel",
	"MailApp_Module_Column_Hide_Tooltip": "Saate sulgeda veeruselektori.",
	"Error_Message_0x80044160_Title": "Teil puudub juurdepääs",
	"MailApp_Module_Alert_Batch_Untrack_Message": "Kas soovite nende kontaktide jälgimise tühistada ja nad teenuses Dynamics 365 alles hoida või soovite nad ka teenusest Dynamics 365 kustutada?",
	"MoCA_OWA_No_Past_Activities": "Varasemad tegevused puuduvad.",
	"MailApp_Module_Column_Department": "Osakond",
	"MoCA_OWA_Next_Activity_Label": "Järgmine tegevus",
	"MailApp.Generic.ActivityId": "Tegevuse ID: {0} \n Kuupäev: {1}",
	"Form_Editor_Command_Group_New": "Loo",
	"MailApp_Module_Alert_Link_Batch_Error_If_Pending_Untrack": "Me ei saa mõningaid neist kontaktidest linkida, sest nende olek on Jälgimise lõpetamine on ootel.",
	"MoCA_OWA_Client_Loading_Message": "Rakenduse lähtestamine …",
	"Error_Message_0x8005f201": "Teie ettevõtte süsteemi installitud keel pole rakenduses saadaval.\nVõtke toetatud keele seadistamiseks ühendust süsteemiadministraatoriga.",
	"MailApp_Module_Filter_Hide_Tooltip": "Saate filtrid välja lülitada.",
	"MailApp_Module_Untrack_Tooltip": "Saate tühistada kontaktide jälgimise teenuses Dynamics 365.",
	"MailApp_Module_Alert_Transaction_Unrack_Error": "Midagi läks valesti. Mõnede kontaktide jälgimist ei lõpetatud.",
	"MailApp_Module_Column_Business_Phone": "Töötelefon",
	"Error_Message_0x8005f204": "Me ei saanud teie Microsoft Dynamics 365 serveriga ühendada. Sulgege rakendus ja avage see uuesti.",
	"MailApp_Module_Alert_Untrack_Single_Error_If_Not_Tracked": "Te ei saa selle kontakti jälgimist lõpetada, sest kontakti olek on Ei jälgita.",
	"MailApp_Module_Link_Tooltip": "Saate linkida kontakti teenuse Dynamics 365 kontodega.",
	"Error_Message_0x80061211_Title": "Meiliaadressi pole meie süsteemis",
	"MailApp_Module_Dymamics_365_Link_Alert": "Määrasite peamise kontakti Dynamics CRM-i kontaktide vahekaardilt. Kasutage peamise kontakti määramiseks Outlooki kontaktide vahekaarti.",
	"MailApp_Module_Paging_Last": "Viimane",
	"MailApp_Module_Link_Button_Cancel": "Tühista",
	"MoCA_OWA_Client_Download_Metadata_Message": "Metaandmete allalaadimine …",
	"MailApp_Module_Alert_Untrack_Single_Error_If_Pending_Tracked": "Te ei saa selle kontakti jälgimist lõpetada, sest kontakti olek on Jälgimine on ootel.",
	"MailApp_Module_Alert_Button_Cancel": "Tühista",
	"MailApp_Module_Column_Tracking_Status": "Jälgimisolek",
	"MailApp_Module_Select_Appointment_Alert": "Kohtumise määramiseks valige vähemalt üks kontakt.",
	"Brand_Microsoft": "Microsoft Corporation",
	"MoCA_OWA_Client_Assets_Loading_Message": "Ühenduse loomine teie organisatsiooniga …",
	"MailApp_Module_Select_Track_Alert": "Jälgimiseks valige vähemalt üks kontakt.",
	"MailApp_Module_Link_Button_Cancel_Tooltip": "Saate selle paani sulgeda.",
	"MailApp_Module_Alert_Track_Batch_Error_If_Tracked": "Te ei saa neid kontakte jälgida, sest nende olek on Jälgitav.",
	"MailApp_Module_Untrack": "Tühista jälgimine",
	"MailApp_Module_Tracked": "Jälgitav",
	"Error_Message_0x8005f20f": "Teil pole serveris rakenduse laadimiseks piisavaid õigusi.\nVõtke õiguste värskendamiseks ühendust süsteemiadministraatoriga.",
	"MailApp_Module_Link_Refresh_Message": "Uue konto kuvamiseks ja valitud kontaktidega linkimiseks klõpsake pärast teenuses Dynamics 365 uue konto loomist nuppu Värskenda.",
	"MailApp_Module_Column_Company": "Ettevõte",
	"MailApp_Module_Selected_Contacts_Label": "Valitud kontaktid:",
	"MailApp_Module_Email": "Meil",
	"MailApp_Module_Tracking_Filter_Tracked": "Jälgitavad kontaktid",
	"MoCA_OWA_Client_Processing_Metadata_Message": "Metaandmete töötlemine …",
	"MoCA_OWA_App_DownloadingMetadata": "Vaatame teie Dynamics 365 teavet üle …",
	"MailApp_Module_Dymamics_365_Track_Alert": "Te ei saa neid kontakte jälgida, sest nad on juba teenuses Dynamics CRM olemas.",
	"Error_Message_0x80061202": "Seda rakendust ei saanud laadida, sest teie postkast pole sissetulevate meilide jaoks Microsoft Dynamics 365 serveripoolse sünkroonimisega konfigureeritud. Võtke sissetulevate meilide serveripoolse sünkroonimise seadistamiseks ühendust süsteemiadministraatoriga.",
	"MailApp_Module_Alert_Track_Single_Error_If_Tracked": "Te ei saa seda kontakti jälgida, sest me kuvame kontakti olekuks Jälgitav.",
	"Error_Message_0x80061200": "Teie seadet praegu ei toetata.",
	"Error_Message_0x80061201": "Teie brauserit praegu ei toetata.",
	"Error_Message_0x80061206": "Rakendus pole saadaval teie kasutatava Microsoft Dynamics 365 versiooni jaoks.",
	"MailApp_Module_Link_Button_New_Tooltip": "Saate luua konto teenuses Dynamics 365.",
	"Error_Message_0x80061205": "Teil pole sellele rakendusele juurdepääsuõigust. Pöörduge oma süsteemiadministraatori poole, et lisada oma kasutajarollile õigus „Dynamics 365 kasutamine Office’i rakenduste jaoks” või eemaldage see rakendus lihtsalt Outlookist. Selleks kasutage Outlooki sätete alal olevat valikut Halda lisandmooduleid.",
	"Error_Message_0x80061208": "Outlooki mobiilibrauseri versiooni ei toetata praegu. Proovige uuesti Outlooki töölauarakendusest.",
	"MailApp_Module_Alert_Batch_Untrack_Title": "Olete nende kontaktide jälgimist lõpetamas.",
	"MailApp_Module_Select_Link_Alert": "Linkimiseks valige vähemalt üks kontakt.",
	"MoCA_OWA_Details_Header": "Üksikasjad",
	"MailApp_Module_Pending_Track": "Jälgimine on ootel",
	"MoCA_OWA_Assets_Loading_Message": "Valmistame asju ette …",
	"MailApp_Module_Appointment": "Ajasta kohtumine.",
	"MoCA_OWA_Authentication_Loading_Message": "Autentimine …",
	"MailApp_Module_Alert_Single_Untrack_Message": "Kas soovite selle kontakti jälgimise tühistada ja ta teenuses Dynamics 365 alles hoida või soovite kontakti ka teenusest Dynamics 365 kustutada?",
	"Error_Message_0x8005f202": "Sellele rakendusele on olemas värskendus. Selle kasutamiseks tuleb rakendus värskendada.",
	"Error_Message_0x8005f203": "Teil puudub õigus selle rakenduse kasutamiseks.\nPaluge süsteemiadministraatoril oma sätted värskendada.",
	"MailApp_Module_Outlook_Contacts": "Outlooki kontaktid",
	"MailApp_Module_Not_Tracked": "Ei jälgita",
	"MailApp_Module_Rows_To_Show": "Kuvatavad read",
	"MailApp_Module_Link_Table_Title": "Lingitava konto valimine",
	"MailApp_Module_Previous": "Eelmine",
	"MailApp_Module_First_Page": "Esimene leht",
	"MailApp_Module_Alert_Transaction_Track_Error": "Midagi läks valesti. Mõningaid kontakte ei jälgita.",
	"MailApp_Module_Alert_Single_Untrack_Title": "Olete lõpetamas selle kontakti jälgimist teenuses Dynamics 365.",
	"MoCA_OWA_Client_Processing_Customizations_Message": "Kohanduste töötlemine …",
	"Error_Message_0x80061218": "Selle Microsoft Dynamics 365 organisatsiooni puhul pole kohtumistel juurdepääs rakendusele lubatud. Kohtumistele juurdepääsu lubamiseks võtke ühendust süsteemiadministraatoriga.",
	"MailApp_Module_Alert_Button_OK": "OK",
	"MailApp_Module_Track_Tooltip": "Saate jälgida kontakte teenuses Dynamics 365.",
	"Error_Message_0x80061217": "Seda rakendust ei saanud laadida, sest teie postkast pole kohtumiste jaoks teenuse Microsoft Dynamics 365 serveripoolse sünkroonimisega konfigureeritud. Võtke kohtumiste serveripoolse sünkroonimise seadistamiseks ühendust süsteemiadministraatoriga.",
	"Error_Message_0x80061216": "Me ei saa rakendust avada, kuna kasutaja postkast on passiivne.",
	"Error_Message_0x80061211": "Tundub, et üritate saada klientrakendusele Microsoft Dynamics 365 rakendus Outlooki jaoks juurdepääsu meiliaadressilt, mida me ei tunne ära. Logige välja ja seejärel uuesti sisse meiliaadressiga, mida kasutate Dynamics 365 jaoks, või paluge oma süsteemiadministraatoril värskendada teie postkasti sätteid, et saaksite kasutada seda meiliaadressi.",
	"Error_Message_0x80061210": "Vaadake, kas brauseri hüpikakende blokeerija blokeerib sisselogimiskuva. Kui jah, siis lubage see hüpikaken ja proovige uuesti. \nKui teil on endiselt sisselogimisega probleeme, proovige lisada usaldusväärsete saitide hulka järgmised URL-id: \n{0} \n{1} \n{2}",
	"Error_Message_0x80061213": "Näib, et teie Outlooki postkasti rakendust pole installitud. Pöörduge oma süsteemiadministraatori poole.",
	"Error_Message_0x80061212": "Te pole Internetiga ühendatud. Looge ühendus ja proovige uuesti.",
	"MailApp_Module_Link_Button_Link": "Lingi"
};