var RESOURCES={
	"MailApp_Module_Notification_Update_In_Progress": "Naujinama.",
	"MailApp_Module_Column_Show_Tooltip": "Norėdami, kad stulpelis būtų rodomas pažymėkite to stulpelio žymės langelį. Išvalykite žymės laukelį, jei norite jį paslėpti.",
	"MailApp_Module_Link_Title": "Saitas",
	"MailApp_Module_Alert_Link_Batch_Message": "Siejame kelis kontaktus su klientais. Tai užtruks vos kelias minutes.",
	"PickList_KBTemplateEditor_Selector_Style_Title": "Pavadinimas",
	"MoCA_OWA_App_Long_Description": "„Dynamics 365“ – tai puikus „Microsoft Dynamics 365“ galios ir „Outlook“ universalumo bei patogumo derinys.\nNaudodami šią pašto programą galėsite:\n[#LI]5D;ieškoti kontaktų arba galimų klientų, kurie jums ką tik parašė el. laišką, „Dynamics 365“ įrašų;[/#LI]5D;\n[#LI]5D;įtraukti žmones kaip „Dynamics 365“ kontaktus ar galimus klientus;[/#LI]5D;\n[#LI]5D;sekti el. laiškus pagal esamus „Dynamics 365“ įrašus;[/#LI]5D;\n[#LI]5D;netgi kurti naujus įrašus, pagal kuriuos galėsite sekti el. laiškus.[/#LI]5D;\nNeleiskite, kad ilgai trunkantis įrašų ieškojimo ir atnaujinimo procesas trukdytų jums dirbti. Naudokite šią „Microsoft Dynamics 365“ programą ir viskas bus po ranka. Informaciją galėsite pasiekti iš bet kurios vietos ir bet kada, tereikės tik prisijungti.\nŠiuo metu šią programą palaiko tik „Outlook 2013“ arba naujesnė versija ir „Outlook Web App“ (tik kompiuterio naršyklės).",
	"Error_Message_0x8005f211": "Ši operacija nesėkminga, nes esate neprisijungęs. Prisijunkite iš naujo ir pabandykite dar kartą.",
	"Error_Message_0x8005f210": "Atsiprašome, inicijuojant programą įvyko klaida. Bandykite dar kartą arba programą paleiskite iš naujo.",
	"Error_Message_0x8005f215": "Įvyko klaida. Šiek tiek palaukite ir bandykite dar kartą. Jei problema kartosis, kreipkitės į sistemos administratorių.",
	"MailApp_Module_Filter_Show_Tooltip": "Įjungiami filtrai.",
	"MailApp_Module_Tracking_Filter_All": "Visi kontaktai",
	"MailApp_Module_Alert_Previously_Tracked_Button_Create": "Kurti naują kontaktą",
	"MailApp_Module_Link_Button_Link_Tooltip": "Susiekite pasirinktą klientą su pasirinktais kontaktais.",
	"MailApp_Module_Unlink": "Atsieti",
	"MailApp_Module_Link": "Saitas",
	"MailApp_Module_Paging_First": "Pirmas",
	"MailApp_Module_Alert_Link_Error_If_Pending_Untrack": "Negalima nustatyti kliento šiam kontaktui, nes jo būsena – Laukiama sekimo anuliavimo.",
	"MailApp_Module_Alert_Track_Single_Error_If_Pending_Untracked": "Negalite sekti šio kontakto, nes nurodoma jo būsena – Laukiama sekimo atšaukimo.",
	"MailApp_Module_Column_Full_Name": "Pavadinimas",
	"Error_Message_0x80061204": "Ši „Dynamics 365“ organizacija neturi prieigos prie programos. Susisiekite su sistemos administratoriumi, kad suteiktų prieigą prie šios programos.",
	"MoCA_OWA_App_Longer": "Jungimasis trunka ilgiau nei įprastai. Vis dar sprendžiame tai.",
	"MailApp_Module_Link_Refresh_Title": "Atnaujinti kliento saitą",
	"Error_Message_0x8004a104": "Negalime prijungti jūsų prie „Microsoft Dynamics 365“ organizacijos, nes dabar ji išjungta. Bandykite dar kartą vėliau.",
	"Error_Message_0x80044160": "Teisės peržiūrėti, kurti, redaguoti arba naikinti duomenis šioje organizacijoje neturite. Pagalbos kreipkitės į administratorių.",
	"MailApp_Module_Refresh_Tooltip": "Atnaujinkite duomenis.",
	"MailApp_Module_Alert_Untrack_Button_Delete": "Atšaukti sekimą ir naikinti",
	"MailApp_Module_Link_Refresh_Button_Cancel": "Atšaukti",
	"MailApp_Module_Track": "Sekti",
	"MailApp_Module_Column_Given_Name": "Vardas",
	"Brand_CRM": "„Microsoft Dynamics 365“",
	"MailApp_Module_Dymamics_365_Contacts": "„Dynamics 365“ kontaktai",
	"MailApp_Module_Link_Button_New": "Naujas",
	"MailApp_Module_Alert_Untrack_Single_Error_If_Pending_Untracked": "Negalite atšaukti šio kontakto sekimo, nes jo būsena – Laukiama sekimo atšaukimo.",
	"MailApp_Module_Column_Office_Location": "Biuro vieta",
	"MailApp_Module_Email_Tooltip": "Siųskite el. laišką.",
	"MailApp_Module_No_Contacts": "Kontaktų nerasta.",
	"MoCA_OWA_Client_Download_Customizations_Message": "Atsisiunčiami tinkinimai...",
	"MailApp_Module_Column_Email": "El. pašto adresas",
	"Error_Message_0x80061210_Title": "Kyla prisijungimo problemų?",
	"MailApp_Module_Select_Untrack_Alert": "Pasirinkite bent vieną nesektiną kontaktą.",
	"MailApp_Module_Alert_Link_Batch_Warning": "Kai kurie iš pasirinktų kontaktų šiuo metu nėra sekami. Jei tęsite, šie kontaktai bus sekami ir jiems bus nustatytas klientas.",
	"MailApp_Module_Search": "Ieškoti",
	"Error_Message_0x80061203": "Turite tik administratoriaus prieigą prie „Microsoft Dynamics 365“. Norėdami naudoti programą, turite turėti skaitymo ir rašymo prieigą.",
	"MailApp_Module_Dymamics_365_Untrack_Alert": "Negalite atšaukti kontaktų sekimo „Dynamics CRM“ skirtuke Kontaktai. Norėdami atšaukti kontaktų sekimą naudokite „Outlook“ skirtuką Kontaktai.",
	"MoCA_OWA_Generic_Error_Title": "Atsiprašome",
	"Error_Message_Generic_Mobile_Client": "Atsiprašome, įvyko klaida. Bandykite dar kartą arba iš naujo paleiskite programą.\nKlaidos kodas: ",
	"MailApp_Module_Alert_Link_Batch_Dont_Show": "Daugiau šio pranešimo nerodyti.",
	"MoCA_OWA_Org_Discovery_Loading_Message": "Ieškoma jūsų organizacija...",
	"MailApp_Module_Tracking_Filter_Untracked": "Nesekami kontaktai",
	"DelveActionHub.TrackingStatus": "Sekimas",
	"MailApp_Module_Select_Email_Alert": "Pasirinkite bent vieną kontaktą, kuriam siųsite el. laišką.",
	"MoCA_OWA_No_Upcoming_Activities": "Būsimos veiklos nėra.",
	"MoCA_OWA_Help_Link_Text": "Padėkite man išspręsti šią problemą",
	"MailApp_Module_Alert_Untrack_Failure_Message": "Nepavyko atšaukti kontakto sekimo. Bandykite dar kartą.",
	"MailApp_Module_Alert_Untrack_Batch_Warning_If_Not_Tracked": "Kai kurie iš pasirinktų kontaktų nėra sekami arba laukiama jų sekimo. Tik sekamų kontaktų sekimas bus atšauktas.",
	"MailApp_Module_Column_Title": "Pareigos",
	"MailApp_Module_Alert_Untrack_Button_Keep": "Atšaukti sekimą ir laikyti",
	"MailApp_Module_Alert_Previously_Tracked": "Anksčiau šis kontaktas buvo sekamas „Dynamics CRM”. Ar norite susieti šį kontaktą su anksčiau sektu kontaktu, ar sukurti naują kontaktą?",
	"MailApp_Module_Next": "Kitas",
	"MoCA_OWA_App_FirstTime": "Tai pirmas kartas, kai jūsų organizacija įkėlė šią programą. Palaukite, kol viską sukonfigūruosime.",
	"MailApp_Module_Alert_Track_Single_Error_If_Pending_Tracked": "Negalite sekti šio kontakto, nes nurodoma jo būsena – Laukiama sekimo.",
	"MailApp_Module_Alert_Task_Error": "Vienu metu galite nustatyti tik vieną kontaktą nurodantį įrašą.",
	"MoCA_OWA_Last_Activity_Label": "Naujausia veikla",
	"MailApp_Module_Alert_Previously_Tracked_Button_Link": "Sieti",
	"MoCA_OWA_App_Short_Description": "Visur ir visada stebėkite el. paštą naudodami „Microsoft Dynamics 365“.",
	"MailApp_Module_Link_Refresh_Button_Refresh": "Atnaujinti",
	"MailApp_Module_Pending_Untrack": "Laukiama sekimo atšaukimo",
	"MailApp_Module_Column_Hide_Tooltip": "Uždarykite stulpelių išrinkiklį.",
	"Error_Message_0x80044160_Title": "Jums nesuteikta prieiga",
	"MailApp_Module_Alert_Batch_Untrack_Message": "Ar norite atšaukti šių kontaktų sekimą ir laikyti juos „Dynamics 365”, ar norite ir panaikinti juos iš „Dynamics 365”?",
	"MoCA_OWA_No_Past_Activities": "Ankstesnės veiklos nėra.",
	"MailApp_Module_Column_Department": "Skyrius",
	"MoCA_OWA_Next_Activity_Label": "Tolesnė veikla",
	"MailApp.Generic.ActivityId": "Veiklos ID: {0} \n Data: {1}",
	"Form_Editor_Command_Group_New": "Kurti",
	"MailApp_Module_Alert_Link_Batch_Error_If_Pending_Untrack": "Negalime susieti keleto iš šių kontaktų, nes jų būsena – Laukiama sekimo anuliavimo.",
	"MoCA_OWA_Client_Loading_Message": "Inicijuojama programa...",
	"Error_Message_0x8005f201": "Įmonės sistemoje įdiegta kalba programoje negalima.\nKreipkitės į sistemos administratorių ir paprašykite, kad nustatytų palaikomą kalbą.",
	"MailApp_Module_Filter_Hide_Tooltip": "Išjungiami filtrai.",
	"MailApp_Module_Untrack_Tooltip": "Atšaukite kontaktų sekimą „Dynamics 365“.",
	"MailApp_Module_Alert_Transaction_Unrack_Error": "Įvyko klaida. Kai kurių kontaktų sekimas nebuvo atšauktas.",
	"MailApp_Module_Column_Business_Phone": "Darbo telefonas",
	"Error_Message_0x8005f204": "Negalime prisijungti prie jūsų „Microsoft Dynamics 365“ serverio. Bandykite uždaryti ir iš naujo atverti programą.",
	"MailApp_Module_Alert_Untrack_Single_Error_If_Not_Tracked": "Negalite atšaukti šio kontakto sekimo, nes jo būsena – Nesekama.",
	"MailApp_Module_Link_Tooltip": "Susiekite kontaktą su klientais „Dynamics 365“.",
	"Error_Message_0x80061211_Title": "El. pašto adreso nėra mūsų sistemoje",
	"MailApp_Module_Dymamics_365_Link_Alert": "Pirminį kontaktą nustatote pasirinkę „Dynamics CRM“ skirtuką Kontaktai. Norėdami nustatyti pirminį kontaktą naudokite „Outlook“ skirtuką Kontaktai.",
	"MailApp_Module_Paging_Last": "Paskutinis",
	"MailApp_Module_Link_Button_Cancel": "Atšaukti",
	"MoCA_OWA_Client_Download_Metadata_Message": "Atsisiunčiami metaduomenys...",
	"MailApp_Module_Alert_Untrack_Single_Error_If_Pending_Tracked": "Negalite atšaukti šio kontakto sekimo, nes jo būsena – Laukiama sekimo.",
	"MailApp_Module_Alert_Button_Cancel": "Atšaukti",
	"MailApp_Module_Column_Tracking_Status": "Sekimo būsena",
	"MailApp_Module_Select_Appointment_Alert": "Pasirinkite bent vieną kontaktą, kuriam nustatysite paskyrą.",
	"Brand_Microsoft": "Microsoft Corporation",
	"MoCA_OWA_Client_Assets_Loading_Message": "Jungiamasi prie jūsų organizacijos...",
	"MailApp_Module_Select_Track_Alert": "Pasirinkite bent vieną sektiną kontaktą.",
	"MailApp_Module_Link_Button_Cancel_Tooltip": "Uždarykite šią sritį.",
	"MailApp_Module_Alert_Track_Batch_Error_If_Tracked": "Negalite sekti šių kontaktų, nes jų būsena – Sekamas.",
	"MailApp_Module_Untrack": "Atšaukti sekimą",
	"MailApp_Module_Tracked": "Sekama",
	"Error_Message_0x8005f20f": "Neturite pakankamai teisių atlikti veiksmus serveryje, todėl negalite įkelti programos.\nKreipkitės į administratorių ir paprašykite jo atnaujinti jūsų teises.",
	"MailApp_Module_Link_Refresh_Message": "Norėdami peržiūrėti ir susieti naują klientą su pasirinktais kontaktais, „Dynamics 365“sukūrę naują klientą spustelėkite Atnaujinti.",
	"MailApp_Module_Column_Company": "Įmonė",
	"MailApp_Module_Selected_Contacts_Label": "Pasirinkti kontaktai:",
	"MailApp_Module_Email": "El. paštas",
	"MailApp_Module_Tracking_Filter_Tracked": "Sekami kontaktai",
	"MoCA_OWA_Client_Processing_Metadata_Message": "Apdorojami metaduomenys...",
	"MoCA_OWA_App_DownloadingMetadata": "Peržiūrime jūsų „Dynamics 365“ informaciją...",
	"MailApp_Module_Dymamics_365_Track_Alert": "Negalite sekti šių kontaktų, nes jų nėra „Dynamics CRM“.",
	"Error_Message_0x80061202": "Negalime įkelti šios programos, nes jūsų el. pašto dėžutė nesukonfigūruota „Microsoft Dynamics 365“ serveryje gaunamiems el. laiškų sinchronizuoti. Susisiekite su sistemos administratoriumi, kad nustatytų gaunamų el. laiškų sinchronizavimą serveryje.",
	"MailApp_Module_Alert_Track_Single_Error_If_Tracked": "Negalite sekti šio kontakto, nes nurodoma jo būsena – Sekama.",
	"Error_Message_0x80061200": "Šiuo metu jūsų įrenginys nepalaikomas.",
	"Error_Message_0x80061201": "Šiuo metu jūsų naršyklė nepalaikoma.",
	"Error_Message_0x80061206": "Su jūsų turima „Microsoft Dynamics 365“ versija ši programa nesuderinama.",
	"MailApp_Module_Link_Button_New_Tooltip": "Sukurkite klientą „Dynamics 365“.",
	"Error_Message_0x80061205": "Neturite teisės pasiekti šią programą. Susisiekite su sistemos administratoriumi, kad teisę \„Naudoti „Dynamics 365 for Office“ programas\“ susietų su jūsų vartotojo vaidmeniu arba tiesiog pašalinkite šią programą iš „Outlook“. Norėdami tai padaryti, naudokite Tvarkyti priedus „Outlook“ parametrų srityje.",
	"Error_Message_0x80061208": "„Outlook“ mobiliosios naršyklės versija šiuo metu nepalaikoma. Bandykite dar kartą iš „Outlook“ darbalaukio programos.",
	"MailApp_Module_Alert_Batch_Untrack_Title": "Ketinate stabdyti šių kontaktų sekimą.",
	"MailApp_Module_Select_Link_Alert": "Pasirinkite bent vieną susietiną kontaktą.",
	"MoCA_OWA_Details_Header": "Informacija",
	"MailApp_Module_Pending_Track": "Laukiama sekimo",
	"MoCA_OWA_Assets_Loading_Message": "Ruošiama...",
	"MailApp_Module_Appointment": "Paskyros planavimas.",
	"MoCA_OWA_Authentication_Loading_Message": "Autentifikuojama...",
	"MailApp_Module_Alert_Single_Untrack_Message": "Ar norite atšaukti šio kontakto sekimą ir laikyti jį „Dynamics 365”, ar norite ir panaikinti jį iš „Dynamics 365”?",
	"Error_Message_0x8005f202": "Siūlomas šios programos naujinimas. Kad galėtumėte naudoti programą, turite ją atnaujinti.",
	"Error_Message_0x8005f203": "Neturite teisų naudoti šios programos.\nPaprašykite, kad sistemos administratorius atnaujintų jūsų parametrus.",
	"MailApp_Module_Outlook_Contacts": "„Outlook“ kontaktai",
	"MailApp_Module_Not_Tracked": "Nesekama",
	"MailApp_Module_Rows_To_Show": "Rodytinos eilutės",
	"MailApp_Module_Link_Table_Title": "Pasirinkti sietiną klientą",
	"MailApp_Module_Previous": "Ankstesnis",
	"MailApp_Module_First_Page": "Pirmasis puslapis",
	"MailApp_Module_Alert_Transaction_Track_Error": "Įvyko klaida. Kai kurie kontaktai nebuvo sekami.",
	"MailApp_Module_Alert_Single_Untrack_Title": "Ketinate stabdyti šio kontakto sekimą „Dynamics 365”.",
	"MoCA_OWA_Client_Processing_Customizations_Message": "Apdorojami tinkinimai...",
	"Error_Message_0x80061218": "Ši „Microsoft Dynamics 365“ organizacija neturi paskyrų prieigos prie programos. Susisiekite su sistemos administratoriumi, kad suteiktų prieigą paskyroms.",
	"MailApp_Module_Alert_Button_OK": "Gerai",
	"MailApp_Module_Track_Tooltip": "Sekite kontaktus „Dynamics 365“.",
	"Error_Message_0x80061217": "Negalime įkelti šios programos, nes jūsų el. pašto dėžutė nesukonfigūruota paskyroms „Microsoft Dynamics 365“ serveryje sinchronizuoti. Susisiekite su sistemos administratoriumi, kad nustatytų paskyrų sinchronizavimą serveryje.",
	"Error_Message_0x80061216": "Negalime atverti programos, nes vartotojo pašto dėžutė neaktyvi.",
	"Error_Message_0x80061211": "Atrodo, kad bandote pasiekti „Microsoft Dynamics 365“ programą, skirtą „Outlook“, naudodami el. pašto adresą, kurio neatpažįstame. Arba atsijunkite ir prisijunkite naudodami el. pašto adresą, kurį naudojate „Dynamics 365“, arba susisiekite su sistemos administratoriumi, kad atnaujintų el. pašto dėžutės parametrus įtraukdamas šį el. pašto adresą.",
	"Error_Message_0x80061210": "Patikrinkite, ar naršyklės iššokančių langų blokavimo programa neblokuoja prisijungimo ekrano. Jei blokuoja, leiskite šį iššokantį langą ir bandykite dar kartą. \nJei vis tiek nepavyksta prisijungti, pabandykite įtraukti toliau nurodytus URL į patikimų svetainių sąrašą: \n{0} \n{1} \n{2}",
	"Error_Message_0x80061213": "Atrodo, kad programa jūsų „Outlook“ pašto dėžutėje neįdiegta. Kreipkitės į sistemos administratorių.",
	"Error_Message_0x80061212": "Nesate prisijungę prie interneto. Bandykite dar kartą, kai prisijungsite.",
	"MailApp_Module_Link_Button_Link": "Saitas"
};