


--
-- base view for Competitor
--
create view dbo.[Competitor]
 (
    -- logical attributes
    [ModifiedOnBehalfByYomiName],
    [ModifiedByYomiName],
    [CreatedByName],
    [EntityImage],
    [ModifiedByName],
    [ModifiedOnBehalfByName],
    [TransactionCurrencyIdName],
    [CreatedOnBehalfByYomiName],
    [CreatedByYomiName],
    [OrganizationIdName],
    [CreatedOnBehalfByName],
    [EntityImage_Timestamp],
    [EntityImage_URL],

    -- linked address entities
    [Address1_AddressTypeCode],
    [Address1_City],
    [Address1_AddressId],
    [Address1_Composite],
    [Address1_Country],
    [Address1_County],
    [Address1_Fax],
    [Address1_Latitude],
    [Address1_Line1],
    [Address1_Line2],
    [Address1_Line3],
    [Address1_Longitude],
    [Address1_Name],
    [Address1_PostalCode],
    [Address1_PostOfficeBox],
    [Address1_ShippingMethodCode],
    [Address1_StateOrProvince],
    [Address1_Telephone1],
    [Address1_Telephone2],
    [Address1_Telephone3],
    [Address1_UPSZone],
    [Address1_UTCOffset],

    [Address2_AddressTypeCode],
    [Address2_City],
    [Address2_AddressId],
    [Address2_Composite],
    [Address2_Country],
    [Address2_County],
    [Address2_Fax],
    [Address2_Latitude],
    [Address2_Line1],
    [Address2_Line2],
    [Address2_Line3],
    [Address2_Longitude],
    [Address2_Name],
    [Address2_PostalCode],
    [Address2_PostOfficeBox],
    [Address2_ShippingMethodCode],
    [Address2_StateOrProvince],
    [Address2_Telephone1],
    [Address2_Telephone2],
    [Address2_Telephone3],
    [Address2_UPSZone],
    [Address2_UTCOffset],

    -- physical attributes
    [CompetitorId],
    [OrganizationId],
    [Name],
    [Overview],
    [ReferenceInfoUrl],
    [ReportedRevenue],
    [ReportingQuarter],
    [ReportingYear],
    [Strengths],
    [Weaknesses],
    [Opportunities],
    [Threats],
    [TickerSymbol],
    [KeyProduct],
    [StockExchange],
    [WinPercentage],
    [WebSiteUrl],
    [CreatedOn],
    [CreatedBy],
    [ModifiedOn],
    [ModifiedBy],
    [VersionNumber],
    [UTCConversionTimeZoneCode],
    [TimeZoneRuleVersionNumber],
    [OverriddenCreatedOn],
    [ExchangeRate],
    [TransactionCurrencyId],
    [ImportSequenceNumber],
    [ReportedRevenue_Base],
    [YomiName],
    [CreatedOnBehalfBy],
    [ModifiedOnBehalfBy],
    [EntityImageId],
    [ProcessId],
    [StageId]
) with view_metadata as
select
    -- logical attributes
    [lk_competitorbase_modifiedonbehalfby].[YomiFullName],
    [lk_competitorbase_modifiedby].[YomiFullName],
    [lk_competitorbase_createdby].[FullName],
    [lk_competitor_entityimage].[ImageData],
    [lk_competitorbase_modifiedby].[FullName],
    [lk_competitorbase_modifiedonbehalfby].[FullName],
    [transactioncurrency_competitor].[CurrencyName],
    [lk_competitorbase_createdonbehalfby].[YomiFullName],
    [lk_competitorbase_createdby].[YomiFullName],
    [organization_competitors].[Name],
    [lk_competitorbase_createdonbehalfby].[FullName],
    [lk_competitor_entityimage].[ImageTimestamp],
    [lk_competitor_entityimage].[ImageURL],

    -- linked address entities
    [XXaddress1].[AddressTypeCode],
    [XXaddress1].[City],
    [XXaddress1].[CompetitorAddressId],
    [XXaddress1].[Composite],
    [XXaddress1].[Country],
    [XXaddress1].[County],
    [XXaddress1].[Fax],
    [XXaddress1].[Latitude],
    [XXaddress1].[Line1],
    [XXaddress1].[Line2],
    [XXaddress1].[Line3],
    [XXaddress1].[Longitude],
    [XXaddress1].[Name],
    [XXaddress1].[PostalCode],
    [XXaddress1].[PostOfficeBox],
    [XXaddress1].[ShippingMethodCode],
    [XXaddress1].[StateOrProvince],
    [XXaddress1].[Telephone1],
    [XXaddress1].[Telephone2],
    [XXaddress1].[Telephone3],
    [XXaddress1].[UPSZone],
    [XXaddress1].[UTCOffset],
    [XXaddress2].[AddressTypeCode],
    [XXaddress2].[City],
    [XXaddress2].[CompetitorAddressId],
    [XXaddress2].[Composite],
    [XXaddress2].[Country],
    [XXaddress2].[County],
    [XXaddress2].[Fax],
    [XXaddress2].[Latitude],
    [XXaddress2].[Line1],
    [XXaddress2].[Line2],
    [XXaddress2].[Line3],
    [XXaddress2].[Longitude],
    [XXaddress2].[Name],
    [XXaddress2].[PostalCode],
    [XXaddress2].[PostOfficeBox],
    [XXaddress2].[ShippingMethodCode],
    [XXaddress2].[StateOrProvince],
    [XXaddress2].[Telephone1],
    [XXaddress2].[Telephone2],
    [XXaddress2].[Telephone3],
    [XXaddress2].[UPSZone],
    [XXaddress2].[UTCOffset],
    -- physical attribute
    [CompetitorBase].[CompetitorId],
    [CompetitorBase].[OrganizationId],
    [CompetitorBase].[Name],
    [CompetitorBase].[Overview],
    [CompetitorBase].[ReferenceInfoUrl],
    [CompetitorBase].[ReportedRevenue],
    [CompetitorBase].[ReportingQuarter],
    [CompetitorBase].[ReportingYear],
    [CompetitorBase].[Strengths],
    [CompetitorBase].[Weaknesses],
    [CompetitorBase].[Opportunities],
    [CompetitorBase].[Threats],
    [CompetitorBase].[TickerSymbol],
    [CompetitorBase].[KeyProduct],
    [CompetitorBase].[StockExchange],
    [CompetitorBase].[WinPercentage],
    [CompetitorBase].[WebSiteUrl],
    [CompetitorBase].[CreatedOn],
    [CompetitorBase].[CreatedBy],
    [CompetitorBase].[ModifiedOn],
    [CompetitorBase].[ModifiedBy],
    [CompetitorBase].[VersionNumber],
    [CompetitorBase].[UTCConversionTimeZoneCode],
    [CompetitorBase].[TimeZoneRuleVersionNumber],
    [CompetitorBase].[OverriddenCreatedOn],
    [CompetitorBase].[ExchangeRate],
    [CompetitorBase].[TransactionCurrencyId],
    [CompetitorBase].[ImportSequenceNumber],
    [CompetitorBase].[ReportedRevenue_Base],
    [CompetitorBase].[YomiName],
    [CompetitorBase].[CreatedOnBehalfBy],
    [CompetitorBase].[ModifiedOnBehalfBy],
    [CompetitorBase].[EntityImageId],
    [CompetitorBase].[ProcessId],
    [CompetitorBase].[StageId]
from [CompetitorBase] 
    left join [CompetitorAddressBase] XXaddress1 on ([CompetitorBase].[CompetitorId] = XXaddress1.ParentId and XXaddress1.AddressNumber = 1)
    left join [CompetitorAddressBase] XXaddress2 on ([CompetitorBase].[CompetitorId] = XXaddress2.ParentId and XXaddress2.AddressNumber = 2)
    left join [ImageDescriptor] [lk_competitor_entityimage] on ([CompetitorBase].[EntityImageId] = [lk_competitor_entityimage].[ImageDescriptorId])
    left join [SystemUserBase] [lk_competitorbase_createdby] with(nolock) on ([CompetitorBase].[CreatedBy] = [lk_competitorbase_createdby].[SystemUserId])
    left join [SystemUserBase] [lk_competitorbase_createdonbehalfby] with(nolock) on ([CompetitorBase].[CreatedOnBehalfBy] = [lk_competitorbase_createdonbehalfby].[SystemUserId])
    left join [SystemUserBase] [lk_competitorbase_modifiedby] with(nolock) on ([CompetitorBase].[ModifiedBy] = [lk_competitorbase_modifiedby].[SystemUserId])
    left join [SystemUserBase] [lk_competitorbase_modifiedonbehalfby] with(nolock) on ([CompetitorBase].[ModifiedOnBehalfBy] = [lk_competitorbase_modifiedonbehalfby].[SystemUserId])
    left join [OrganizationBase] [organization_competitors] with(nolock) on ([CompetitorBase].[OrganizationId] = [organization_competitors].[OrganizationId])
    left join [TransactionCurrencyBase] [transactioncurrency_competitor] on ([CompetitorBase].[TransactionCurrencyId] = [transactioncurrency_competitor].[TransactionCurrencyId])
