CREATE TABLE [dbo].[activitymonitorBase] (
    [activitymonitorId]           UNIQUEIDENTIFIER NOT NULL,
    [CreatedOn]                   DATETIME         NULL,
    [CreatedBy]                   UNIQUEIDENTIFIER NULL,
    [ModifiedOn]                  DATETIME         NULL,
    [ModifiedBy]                  UNIQUEIDENTIFIER NULL,
    [CreatedOnBehalfBy]           UNIQUEIDENTIFIER NULL,
    [ModifiedOnBehalfBy]          UNIQUEIDENTIFIER NULL,
    [OwnerId]                     UNIQUEIDENTIFIER NOT NULL,
    [OwnerIdType]                 INT              CONSTRAINT [DF_activitymonitorBase_OwnerIdType] DEFAULT ((8)) NOT NULL,
    [OwningBusinessUnit]          UNIQUEIDENTIFIER NULL,
    [statecode]                   INT              NOT NULL,
    [statuscode]                  INT              NULL,
    [VersionNumber]               ROWVERSION       NULL,
    [ImportSequenceNumber]        INT              NULL,
    [OverriddenCreatedOn]         DATETIME         NULL,
    [TimeZoneRuleVersionNumber]   INT              NULL,
    [UTCConversionTimeZoneCode]   INT              NULL,
    [Name]                        NVARCHAR (100)   NULL,
    [EntitlementCheck]            BIT              NULL,
    [ContactCreatedByRule]        BIT              NULL,
    [CurrentState]                INT              NULL,
    [Reason]                      INT              NULL,
    [MonitoredActivityItemId]     UNIQUEIDENTIFIER NULL,
    [AdvancedSettings]            NVARCHAR (1000)  NULL,
    [RuleId]                      UNIQUEIDENTIFIER NULL,
    [ConditionId]                 UNIQUEIDENTIFIER NULL,
    [MonitoredActivityItemIdName] NVARCHAR (4000)  NULL,
    [MonitoredActivityItemIdType] INT              NULL,
    CONSTRAINT [PK_activitymonitorBase] PRIMARY KEY CLUSTERED ([activitymonitorId] ASC) WITH (FILLFACTOR = 100, DATA_COMPRESSION = ROW),
    CONSTRAINT [business_unit_activitymonitor] FOREIGN KEY ([OwningBusinessUnit]) REFERENCES [dbo].[BusinessUnitBase] ([BusinessUnitId]),
    CONSTRAINT [convertrule_activitymonitor] FOREIGN KEY ([RuleId]) REFERENCES [dbo].[ConvertRuleBaseIds] ([ConvertRuleId]),
    CONSTRAINT [convertruleitem_activitymonitor] FOREIGN KEY ([ConditionId]) REFERENCES [dbo].[ConvertRuleItemBaseIds] ([ConvertRuleItemId]),
    CONSTRAINT [owner_activitymonitor] FOREIGN KEY ([OwnerId]) REFERENCES [dbo].[OwnerBase] ([OwnerId])
);

