CREATE TABLE [dbo].[SLABaseIds] (
    [SLAId] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_SLABaseIds] PRIMARY KEY CLUSTERED ([SLAId] ASC)
);


GO
ALTER TABLE [dbo].[SLABaseIds] SET (LOCK_ESCALATION = DISABLE);

