CREATE TABLE [dbo].[SLAItemBaseIds] (
    [SLAItemId] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_SLAItemBaseIds] PRIMARY KEY CLUSTERED ([SLAItemId] ASC)
);


GO
ALTER TABLE [dbo].[SLAItemBaseIds] SET (LOCK_ESCALATION = DISABLE);

