


--
-- base view for SalesOrderDetail
--
create view dbo.[SalesOrderDetail]
 (
    -- logical attributes
    [ProductIdName],
    [OwnerId],
    [OwnerIdType],
    [SalesOrderIdName],
    [QuoteDetailIdName],
    [SalesOrderStateCode],
    [OwningBusinessUnit],
    [SalesOrderIsPriceLocked],
    [OwningUser],
    [SalesRepIdYomiName],
    [CreatedByName],
    [CreatedByYomiName],
    [CreatedOnBehalfByName],
    [CreatedOnBehalfByYomiName],
    [ModifiedByName],
    [ModifiedByYomiName],
    [ModifiedOnBehalfByName],
    [ModifiedOnBehalfByYomiName],
    [SalesRepIdName],
    [UoMIdName],
    [TransactionCurrencyIdName],

    -- ownership entries
    OwnerIdName,
    OwnerIdYomiName,
    OwnerIdDsc,
    OwningTeam,

    -- physical attributes
    [SalesOrderDetailId],
    [CreatedOn],
    [CreatedBy],
    [ModifiedOn],
    [ModifiedBy],
    [CreatedOnBehalfBy],
    [ModifiedOnBehalfBy],
    [VersionNumber],
    [ImportSequenceNumber],
    [OverriddenCreatedOn],
    [TimeZoneRuleVersionNumber],
    [UTCConversionTimeZoneCode],
    [BaseAmount],
    [TransactionCurrencyId],
    [ExchangeRate],
    [BaseAmount_Base],
    [Description],
    [ExtendedAmount],
    [ExtendedAmount_Base],
    [IsCopied],
    [IsPriceOverridden],
    [IsProductOverridden],
    [LineItemNumber],
    [ManualDiscountAmount],
    [ManualDiscountAmount_Base],
    [ParentBundleId],
    [ProductAssociationId],
    [ProductTypeCode],
    [PricePerUnit],
    [PricePerUnit_Base],
    [PricingErrorCode],
    [ProductDescription],
    [ProductName],
    [ProductId],
    [Quantity],
    [QuantityBackordered],
    [QuantityCancelled],
    [QuantityShipped],
    [RequestDeliveryBy],
    [SalesOrderId],
    [SalesRepId],
    [ShipTo_AddressId],
    [ShipTo_City],
    [ShipTo_ContactName],
    [ShipTo_Country],
    [ShipTo_Fax],
    [ShipTo_FreightTermsCode],
    [ShipTo_Line1],
    [ShipTo_Line2],
    [ShipTo_Line3],
    [ShipTo_Name],
    [ShipTo_PostalCode],
    [ShipTo_StateOrProvince],
    [ShipTo_Telephone],
    [Tax],
    [Tax_Base],
    [UoMId],
    [VolumeDiscountAmount],
    [VolumeDiscountAmount_Base],
    [WillCall],
    [SequenceNumber],
    [PropertyConfigurationStatus],
    [QuoteDetailId],
    [SalesOrderDetailName],
    [ParentBundleIdRef],
    [SkipPriceCalculation],
    [ProductNumber]
) with view_metadata as
select
    -- logical attributes
    [product_order_details].[Name],
    [order_details].[OwnerId],
    [order_details].[OwnerIdType],
    [order_details].[Name],
    [msdyn_quotedetail_salesorderdetail].[QuoteDetailName],
    [order_details].[StateCode],
    [order_details].[OwningBusinessUnit],
    [order_details].[IsPriceLocked],
    case when [order_details].OwnerIdType = 8
    then [order_details].OwnerId
    else null
    end,
    [system_user_salesorderdetail].[YomiFullName],
    [lk_salesorderdetailbase_createdby].[FullName],
    [lk_salesorderdetailbase_createdby].[YomiFullName],
    [lk_salesorderdetailbase_createdonbehalfby].[FullName],
    [lk_salesorderdetailbase_createdonbehalfby].[YomiFullName],
    [lk_salesorderdetailbase_modifiedby].[FullName],
    [lk_salesorderdetailbase_modifiedby].[YomiFullName],
    [lk_salesorderdetailbase_modifiedonbehalfby].[FullName],
    [lk_salesorderdetailbase_modifiedonbehalfby].[YomiFullName],
    [system_user_salesorderdetail].[FullName],
    [unit_of_measurement_order_details].[Name],
    [transactioncurrency_salesorderdetail].[CurrencyName],

    -- ownership entries
    OwnerName = XXowner.Name,
    OwnerYomiName =  XXowner.YomiName,
    OwnerDsc = 0, -- DSC is removed, stub it to 0
    OwningTeam = case 
 		when XXowner.OwnerIdType= 9 then XXowner.OwnerId
		else null
		end,

    -- physical attribute
    [SalesOrderDetailBase].[SalesOrderDetailId],
    [SalesOrderDetailBase].[CreatedOn],
    [SalesOrderDetailBase].[CreatedBy],
    [SalesOrderDetailBase].[ModifiedOn],
    [SalesOrderDetailBase].[ModifiedBy],
    [SalesOrderDetailBase].[CreatedOnBehalfBy],
    [SalesOrderDetailBase].[ModifiedOnBehalfBy],
    [SalesOrderDetailBase].[VersionNumber],
    [SalesOrderDetailBase].[ImportSequenceNumber],
    [SalesOrderDetailBase].[OverriddenCreatedOn],
    [SalesOrderDetailBase].[TimeZoneRuleVersionNumber],
    [SalesOrderDetailBase].[UTCConversionTimeZoneCode],
    [SalesOrderDetailBase].[BaseAmount],
    [SalesOrderDetailBase].[TransactionCurrencyId],
    [SalesOrderDetailBase].[ExchangeRate],
    [SalesOrderDetailBase].[BaseAmount_Base],
    [SalesOrderDetailBase].[Description],
    [SalesOrderDetailBase].[ExtendedAmount],
    [SalesOrderDetailBase].[ExtendedAmount_Base],
    [SalesOrderDetailBase].[IsCopied],
    [SalesOrderDetailBase].[IsPriceOverridden],
    [SalesOrderDetailBase].[IsProductOverridden],
    [SalesOrderDetailBase].[LineItemNumber],
    [SalesOrderDetailBase].[ManualDiscountAmount],
    [SalesOrderDetailBase].[ManualDiscountAmount_Base],
    [SalesOrderDetailBase].[ParentBundleId],
    [SalesOrderDetailBase].[ProductAssociationId],
    [SalesOrderDetailBase].[ProductTypeCode],
    [SalesOrderDetailBase].[PricePerUnit],
    [SalesOrderDetailBase].[PricePerUnit_Base],
    [SalesOrderDetailBase].[PricingErrorCode],
    [SalesOrderDetailBase].[ProductDescription],
    [SalesOrderDetailBase].[ProductName],
    [SalesOrderDetailBase].[ProductId],
    [SalesOrderDetailBase].[Quantity],
    [SalesOrderDetailBase].[QuantityBackordered],
    [SalesOrderDetailBase].[QuantityCancelled],
    [SalesOrderDetailBase].[QuantityShipped],
    [SalesOrderDetailBase].[RequestDeliveryBy],
    [SalesOrderDetailBase].[SalesOrderId],
    [SalesOrderDetailBase].[SalesRepId],
    [SalesOrderDetailBase].[ShipTo_AddressId],
    [SalesOrderDetailBase].[ShipTo_City],
    [SalesOrderDetailBase].[ShipTo_ContactName],
    [SalesOrderDetailBase].[ShipTo_Country],
    [SalesOrderDetailBase].[ShipTo_Fax],
    [SalesOrderDetailBase].[ShipTo_FreightTermsCode],
    [SalesOrderDetailBase].[ShipTo_Line1],
    [SalesOrderDetailBase].[ShipTo_Line2],
    [SalesOrderDetailBase].[ShipTo_Line3],
    [SalesOrderDetailBase].[ShipTo_Name],
    [SalesOrderDetailBase].[ShipTo_PostalCode],
    [SalesOrderDetailBase].[ShipTo_StateOrProvince],
    [SalesOrderDetailBase].[ShipTo_Telephone],
    [SalesOrderDetailBase].[Tax],
    [SalesOrderDetailBase].[Tax_Base],
    [SalesOrderDetailBase].[UoMId],
    [SalesOrderDetailBase].[VolumeDiscountAmount],
    [SalesOrderDetailBase].[VolumeDiscountAmount_Base],
    [SalesOrderDetailBase].[WillCall],
    [SalesOrderDetailBase].[SequenceNumber],
    [SalesOrderDetailBase].[PropertyConfigurationStatus],
    [SalesOrderDetailBase].[QuoteDetailId],
    [SalesOrderDetailBase].[SalesOrderDetailName],
    [SalesOrderDetailBase].[ParentBundleIdRef],
    [SalesOrderDetailBase].[SkipPriceCalculation],
    [SalesOrderDetailBase].[ProductNumber]
from [SalesOrderDetailBase] 
    left join [SystemUserBase] [lk_salesorderdetailbase_createdby] on ([SalesOrderDetailBase].[CreatedBy] = [lk_salesorderdetailbase_createdby].[SystemUserId])
    left join [SystemUserBase] [lk_salesorderdetailbase_createdonbehalfby] on ([SalesOrderDetailBase].[CreatedOnBehalfBy] = [lk_salesorderdetailbase_createdonbehalfby].[SystemUserId])
    left join [SystemUserBase] [lk_salesorderdetailbase_modifiedby] on ([SalesOrderDetailBase].[ModifiedBy] = [lk_salesorderdetailbase_modifiedby].[SystemUserId])
    left join [SystemUserBase] [lk_salesorderdetailbase_modifiedonbehalfby] on ([SalesOrderDetailBase].[ModifiedOnBehalfBy] = [lk_salesorderdetailbase_modifiedonbehalfby].[SystemUserId])
    left join [QuoteDetailBase] [msdyn_quotedetail_salesorderdetail] on ([SalesOrderDetailBase].[QuoteDetailId] = [msdyn_quotedetail_salesorderdetail].[QuoteDetailId])
    left join [SalesOrderBase] [order_details] on ([SalesOrderDetailBase].[SalesOrderId] = [order_details].[SalesOrderId])
    left join [ProductBase] [product_order_details] on ([SalesOrderDetailBase].[ProductId] = [product_order_details].[ProductId])
    left join [SystemUserBase] [system_user_salesorderdetail] on ([SalesOrderDetailBase].[SalesRepId] = [system_user_salesorderdetail].[SystemUserId])
    left join [TransactionCurrencyBase] [transactioncurrency_salesorderdetail] on ([SalesOrderDetailBase].[TransactionCurrencyId] = [transactioncurrency_salesorderdetail].[TransactionCurrencyId])
    left join [UoMBase] [unit_of_measurement_order_details] on ([SalesOrderDetailBase].[UoMId] = [unit_of_measurement_order_details].[UoMId])
    left join OwnerBase XXowner on ([order_details].OwnerId = XXowner.OwnerId)
