CREATE TABLE [dbo].[OrganizationBase] (
    [OrganizationId]                                    UNIQUEIDENTIFIER NOT NULL,
    [Name]                                              NVARCHAR (160)   NOT NULL,
    [UserGroupId]                                       UNIQUEIDENTIFIER NULL,
    [PrivilegeUserGroupId]                              UNIQUEIDENTIFIER NULL,
    [FiscalPeriodType]                                  INT              CONSTRAINT [DF_OrganizationBase_FiscalPeriodType] DEFAULT ((2002)) NOT NULL,
    [FiscalCalendarStart]                               DATETIME         NULL,
    [DateFormatCode]                                    INT              CONSTRAINT [Set_To_Zero125] DEFAULT ((0)) NOT NULL,
    [TimeFormatCode]                                    INT              CONSTRAINT [Set_To_Zero126] DEFAULT ((0)) NOT NULL,
    [CurrencySymbol]                                    NVARCHAR (13)    CONSTRAINT [DF_OrganizationBase_CurrencySymbol] DEFAULT ('$') NULL,
    [WeekStartDayCode]                                  INT              CONSTRAINT [Set_To_Zero127] DEFAULT ((0)) NOT NULL,
    [DateSeparator]                                     NVARCHAR (5)     CONSTRAINT [ORG_DATE_SEPARATOR2] DEFAULT ('/') NULL,
    [FullNameConventionCode]                            INT              CONSTRAINT [Set_To_Zero128] DEFAULT ((0)) NOT NULL,
    [NegativeFormatCode]                                INT              CONSTRAINT [Set_To_Zero129] DEFAULT ((0)) NOT NULL,
    [NumberFormat]                                      NVARCHAR (2)     CONSTRAINT [ORG_NUMBER_FORMAT2] DEFAULT ('us') NULL,
    [IsDisabled]                                        BIT              CONSTRAINT [Set_To_Zero130] DEFAULT ((0)) NULL,
    [DisabledReason]                                    NVARCHAR (500)   NULL,
    [KbPrefix]                                          NVARCHAR (20)    CONSTRAINT [DF_OrganizationBase_KbPrefix] DEFAULT ('KBA') NULL,
    [CurrentKbNumber]                                   INT              CONSTRAINT [ORG_LOWER_BOUND_10007] DEFAULT ((1000)) NULL,
    [CasePrefix]                                        NVARCHAR (20)    CONSTRAINT [DF_OrganizationBase_CasePrefix] DEFAULT ('CAS') NULL,
    [CurrentCaseNumber]                                 INT              CONSTRAINT [ORG_LOWER_BOUND_10008] DEFAULT ((1000)) NULL,
    [ContractPrefix]                                    NVARCHAR (20)    CONSTRAINT [DF_OrganizationBase_ContractPrefix] DEFAULT ('CNR') NULL,
    [CurrentContractNumber]                             INT              CONSTRAINT [ORG_LOWER_BOUND_10009] DEFAULT ((1000)) NULL,
    [QuotePrefix]                                       NVARCHAR (20)    CONSTRAINT [DF_OrganizationBase_QuotePrefix] DEFAULT ('QUO') NULL,
    [CurrentQuoteNumber]                                INT              CONSTRAINT [ORG_LOWER_BOUND_100010] DEFAULT ((1000)) NULL,
    [OrderPrefix]                                       NVARCHAR (20)    CONSTRAINT [DF_OrganizationBase_OrderPrefix] DEFAULT ('ORD') NULL,
    [CurrentOrderNumber]                                INT              CONSTRAINT [ORG_LOWER_BOUND_100011] DEFAULT ((1000)) NULL,
    [InvoicePrefix]                                     NVARCHAR (20)    CONSTRAINT [DF_OrganizationBase_InvoicePrefix] DEFAULT ('INV') NULL,
    [CurrentInvoiceNumber]                              INT              CONSTRAINT [ORG_LOWER_BOUND_100012] DEFAULT ((1000)) NULL,
    [UniqueSpecifierLength]                             INT              CONSTRAINT [Unique_Specifier_Length2] DEFAULT ((6)) NULL,
    [CreatedOn]                                         DATETIME         NULL,
    [ModifiedOn]                                        DATETIME         NULL,
    [FiscalYearFormat]                                  NVARCHAR (25)    NULL,
    [FiscalPeriodFormat]                                NVARCHAR (25)    NULL,
    [FiscalYearPeriodConnect]                           NVARCHAR (5)     CONSTRAINT [DF_OrganizationBase_FiscalYearPeriodConnect] DEFAULT ('s') NOT NULL,
    [LanguageCode]                                      INT              NULL,
    [SortId]                                            INT              NULL,
    [DateFormatString]                                  NVARCHAR (255)   NULL,
    [TimeFormatString]                                  NVARCHAR (255)   NULL,
    [PricingDecimalPrecision]                           INT              CONSTRAINT [DF_OrganizationBase_PricingDecimalPrecision] DEFAULT ((2)) NOT NULL,
    [ShowWeekNumber]                                    BIT              CONSTRAINT [Set_To_Zero131] DEFAULT ((0)) NULL,
    [NextTrackingNumber]                                INT              NULL,
    [TagMaxAggressiveCycles]                            TINYINT          CONSTRAINT [DF_OrganizationBase_TagMaxAggressiveCycles] DEFAULT ((2)) NOT NULL,
    [TokenKey]                                          NVARCHAR (90)    NULL,
    [SystemUserId]                                      UNIQUEIDENTIFIER NULL,
    [CreatedBy]                                         UNIQUEIDENTIFIER NULL,
    [GrantAccessToNetworkService]                       BIT              CONSTRAINT [DF_OrganizationBase_GrantAccessToNetworkService] DEFAULT ((0)) NULL,
    [AllowOutlookScheduledSyncs]                        BIT              CONSTRAINT [DF_OrganizationBase_AllowOutlookScheduledSyncs] DEFAULT ((1)) NOT NULL,
    [AllowMarketingEmailExecution]                      BIT              CONSTRAINT [DF_OrganizationBase_AllowMarketingEmailExecution] DEFAULT ((1)) NOT NULL,
    [SqlAccessGroupId]                                  UNIQUEIDENTIFIER NULL,
    [CurrencyFormatCode]                                INT              CONSTRAINT [DF_OrganizationBase_CurrencyFormatCode] DEFAULT ((0)) NOT NULL,
    [FiscalSettingsUpdated]                             BIT              CONSTRAINT [DF_OrganizationBase_FiscalSettingsUpdated] DEFAULT ((0)) NOT NULL,
    [ReportingGroupId]                                  UNIQUEIDENTIFIER NULL,
    [TokenExpiry]                                       SMALLINT         NULL,
    [ShareToPreviousOwnerOnAssign]                      BIT              CONSTRAINT [DF_OrganizationBase_ShareToPreviousOwnerOnAssign] DEFAULT ((1)) NOT NULL,
    [AcknowledgementTemplateId]                         UNIQUEIDENTIFIER NULL,
    [ModifiedBy]                                        UNIQUEIDENTIFIER NULL,
    [IntegrationUserId]                                 UNIQUEIDENTIFIER NULL,
    [TrackingTokenIdBase]                               INT              NULL,
    [BusinessClosureCalendarId]                         UNIQUEIDENTIFIER NULL,
    [AllowAutoUnsubscribeAcknowledgement]               BIT              CONSTRAINT [DF_OrganizationBase_AllowAutoUnsubscribeAcknowledgement] DEFAULT ((0)) NULL,
    [AllowAutoUnsubscribe]                              BIT              CONSTRAINT [DF_OrganizationBase_AllowAutoUnsubscribe] DEFAULT ((0)) NULL,
    [Picture]                                           NVARCHAR (MAX)   NULL,
    [VersionNumber]                                     ROWVERSION       NULL,
    [TrackingPrefix]                                    NVARCHAR (256)   NULL,
    [MinOutlookSyncInterval]                            INT              CONSTRAINT [DF_OrganizationBase_MinOutlookSyncInterval] DEFAULT ((900000)) NOT NULL,
    [BulkOperationPrefix]                               NVARCHAR (20)    CONSTRAINT [DF_OrganizationBase_BulkOperationPrefix] DEFAULT ('BO') NOT NULL,
    [AllowAutoResponseCreation]                         BIT              CONSTRAINT [DF_OrganizationBase_AllowAutoResponseCreation] DEFAULT ((1)) NULL,
    [MaximumTrackingNumber]                             INT              NULL,
    [CampaignPrefix]                                    NVARCHAR (20)    CONSTRAINT [DF_OrganizationBase_CampaignPrefix] DEFAULT ('CMP') NOT NULL,
    [SqlAccessGroupName]                                NVARCHAR (256)   NULL,
    [CurrentCampaignNumber]                             INT              CONSTRAINT [DF_OrganizationBase_CurrentCampaignNumber] DEFAULT ((1000)) NULL,
    [FiscalYearDisplayCode]                             TINYINT          CONSTRAINT [DF_OrganizationBase_FiscalYearDisplayCode] DEFAULT ((1)) NOT NULL,
    [SiteMapXml]                                        NVARCHAR (MAX)   NULL,
    [IsRegistered]                                      BIT              CONSTRAINT [DF_OrganizationBase_IsRegistered] DEFAULT ((0)) NULL,
    [ReportingGroupName]                                NVARCHAR (256)   NULL,
    [CurrentBulkOperationNumber]                        INT              CONSTRAINT [DF_OrganizationBase_CurrentBulkOperationNumber] DEFAULT ((1000)) NULL,
    [SchemaNamePrefix]                                  NVARCHAR (8)     CONSTRAINT [DF_OrganizationBase_SchemaNamePrefix] DEFAULT ('new') NULL,
    [IgnoreInternalEmail]                               BIT              CONSTRAINT [DF_OrganizationBase_IgnoreInternalEmail] DEFAULT ((0)) NOT NULL,
    [TagPollingPeriod]                                  INT              CONSTRAINT [DF_OrganizationBase_TagPollingPeriod] DEFAULT ((600000)) NOT NULL,
    [TrackingTokenIdDigits]                             TINYINT          NULL,
    [NumberGroupFormat]                                 NVARCHAR (50)    NULL,
    [LongDateFormatCode]                                INT              CONSTRAINT [DF_OrganizationBase_LongDateFormatCode] DEFAULT ((0)) NOT NULL,
    [UTCConversionTimeZoneCode]                         INT              NULL,
    [TimeZoneRuleVersionNumber]                         INT              NULL,
    [CurrentImportSequenceNumber]                       INT              CONSTRAINT [DF_OrganizationBase_CurrentImportSequenceNumber] DEFAULT ((1)) NOT NULL,
    [ParsedTablePrefix]                                 NVARCHAR (20)    CONSTRAINT [DF_OrganizationBase_ParsedTablePrefix] DEFAULT ('PIF') NOT NULL,
    [V3CalloutConfigHash]                               NVARCHAR (256)   NULL,
    [IsFiscalPeriodMonthBased]                          BIT              CONSTRAINT [DF_OrganizationBase_IsFiscalPeriodMonthBased] DEFAULT ((0)) NOT NULL,
    [LocaleId]                                          INT              NOT NULL,
    [ParsedTableColumnPrefix]                           NVARCHAR (20)    CONSTRAINT [DF_OrganizationBase_ParsedTableColumnPrefix] DEFAULT ('COL') NOT NULL,
    [SupportUserId]                                     UNIQUEIDENTIFIER NULL,
    [AMDesignator]                                      NVARCHAR (25)    CONSTRAINT [DF_OrganizationBase_AMDesignator] DEFAULT ('AM') NOT NULL,
    [CurrencyDisplayOption]                             INT              CONSTRAINT [DF_OrganizationBase_CurrencyDisplayOption] DEFAULT ((0)) NOT NULL,
    [MinAddressBookSyncInterval]                        INT              CONSTRAINT [DF_OrganizationBase_MinAddressBookSyncInterval] DEFAULT ((3600000)) NOT NULL,
    [IsDuplicateDetectionEnabledForOnlineCreateUpdate]  BIT              CONSTRAINT [DF_OrganizationBase_IsDuplicateDetectionEnabledForOnlineCreateUpdate] DEFAULT ((1)) NOT NULL,
    [FeatureSet]                                        NVARCHAR (MAX)   NULL,
    [BlockedAttachments]                                NVARCHAR (MAX)   NULL,
    [IsDuplicateDetectionEnabledForOfflineSync]         BIT              CONSTRAINT [DF_OrganizationBase_IsDuplicateDetectionEnabledForOfflineSync] DEFAULT ((1)) NOT NULL,
    [AllowOfflineScheduledSyncs]                        BIT              CONSTRAINT [DF_OrganizationBase_AllowOfflineScheduledSyncs] DEFAULT ((1)) NOT NULL,
    [AllowUnresolvedPartiesOnEmailSend]                 BIT              CONSTRAINT [DF_OrganizationBase_AllowUnresolvedPartiesOnEmailSend] DEFAULT ((0)) NOT NULL,
    [TimeSeparator]                                     NVARCHAR (5)     NULL,
    [CurrentParsedTableNumber]                          INT              CONSTRAINT [DF_OrganizationBase_CurrentParsedTableNumber] DEFAULT ((1)) NOT NULL,
    [MinOfflineSyncInterval]                            INT              CONSTRAINT [DF_OrganizationBase_MinOfflineSyncInterval] DEFAULT ((900000)) NOT NULL,
    [AllowWebExcelExport]                               BIT              CONSTRAINT [DF_OrganizationBase_AllowWebExcelExport] DEFAULT ((1)) NOT NULL,
    [ReferenceSiteMapXml]                               NVARCHAR (MAX)   NULL,
    [IsDuplicateDetectionEnabledForImport]              BIT              CONSTRAINT [DF_OrganizationBase_IsDuplicateDetectionEnabledForImport] DEFAULT ((1)) NOT NULL,
    [CalendarType]                                      INT              CONSTRAINT [DF_OrganizationBase_CalendarType] DEFAULT ((2)) NULL,
    [SQMEnabled]                                        BIT              CONSTRAINT [DF_OrganizationBase_SQMEnabled] DEFAULT ((0)) NULL,
    [NegativeCurrencyFormatCode]                        INT              CONSTRAINT [DF_OrganizationBase_NegativeCurrencyFormatCode] DEFAULT ((0)) NOT NULL,
    [AllowAddressBookSyncs]                             BIT              CONSTRAINT [DF_OrganizationBase_AllowAddressBookSyncs] DEFAULT ((1)) NOT NULL,
    [ISVIntegrationCode]                                INT              CONSTRAINT [DF_OrganizationBase_ISVIntegrationCode] DEFAULT ((0)) NOT NULL,
    [DecimalSymbol]                                     NVARCHAR (5)     CONSTRAINT [DF_OrganizationBase_DecimalSymbol] DEFAULT ('.') NOT NULL,
    [MaxUploadFileSize]                                 INT              CONSTRAINT [DF_OrganizationBase_MaxUploadFileSize] DEFAULT ((5242880)) NOT NULL,
    [IsAppMode]                                         BIT              CONSTRAINT [DF_OrganizationBase_IsAppMode] DEFAULT ((0)) NOT NULL,
    [EnablePricingOnCreate]                             BIT              CONSTRAINT [DF_OrganizationBase_EnablePricingOnCreate] DEFAULT ((1)) NOT NULL,
    [IsSOPIntegrationEnabled]                           BIT              CONSTRAINT [DF_OrganizationBase_IsSOPIntegrationEnabled] DEFAULT ((0)) NOT NULL,
    [PMDesignator]                                      NVARCHAR (25)    CONSTRAINT [DF_OrganizationBase_PMDesignator] DEFAULT ('PM') NOT NULL,
    [CurrencyDecimalPrecision]                          INT              CONSTRAINT [DF_OrganizationBase_CurrencyDecimalPrecision] DEFAULT ((2)) NOT NULL,
    [MaxAppointmentDurationDays]                        INT              CONSTRAINT [DF_OrganizationBase_MaxAppointmentDurationDays] DEFAULT ((10)) NOT NULL,
    [EmailSendPollingPeriod]                            INT              CONSTRAINT [DF_OrganizationBase_EmailSendPollingPeriod] DEFAULT ((600000)) NOT NULL,
    [RenderSecureIFrameForEmail]                        BIT              CONSTRAINT [DF_OrganizationBase_RenderSecureIFrameForEmail] DEFAULT ((0)) NOT NULL,
    [NumberSeparator]                                   NVARCHAR (5)     CONSTRAINT [DF_OrganizationBase_NumberSeparator] DEFAULT (',') NOT NULL,
    [PrivReportingGroupId]                              UNIQUEIDENTIFIER NULL,
    [BaseCurrencyId]                                    UNIQUEIDENTIFIER NULL,
    [MaxRecordsForExportToExcel]                        INT              CONSTRAINT [DF_OrganizationBase_MaxRecordsForExportToExcel] DEFAULT ((10000)) NOT NULL,
    [PrivReportingGroupName]                            NVARCHAR (256)   NULL,
    [YearStartWeekCode]                                 INT              CONSTRAINT [DF_OrganizationBase_YearStartWeekCode] DEFAULT ((0)) NOT NULL,
    [IsPresenceEnabled]                                 BIT              CONSTRAINT [DF_OrganizationBase_IsPresenceEnabled] DEFAULT ((1)) NULL,
    [IsDuplicateDetectionEnabled]                       BIT              CONSTRAINT [DF_OrganizationBase_IsDuplicateDetectionEnabled] DEFAULT ((1)) NOT NULL,
    [RecurrenceExpansionJobBatchInterval]               INT              CONSTRAINT [DF_OrganizationBase_RecurrenceExpansionJobBatchInterval] DEFAULT ((0)) NOT NULL,
    [DefaultRecurrenceEndRangeType]                     INT              CONSTRAINT [DF_OrganizationBase_DefaultRecurrenceEndRangeType] DEFAULT ((2)) NULL,
    [HashMinAddressCount]                               INT              NULL,
    [RequireApprovalForUserEmail]                       BIT              CONSTRAINT [DF_OrganizationBase_RequireApprovalForUserEmail] DEFAULT ((1)) NOT NULL,
    [RecurrenceDefaultNumberOfOccurrences]              INT              CONSTRAINT [DF_OrganizationBase_RecurrenceDefaultNumberOfOccurrences] DEFAULT ((10)) NOT NULL,
    [ModifiedOnBehalfBy]                                UNIQUEIDENTIFIER NULL,
    [RequireApprovalForQueueEmail]                      BIT              CONSTRAINT [DF_OrganizationBase_RequireApprovalForQueueEmail] DEFAULT ((1)) NOT NULL,
    [AllowEntityOnlyAudit]                              BIT              CONSTRAINT [DF_OrganizationBase_AllowEntityOnlyAudit] DEFAULT ((1)) NOT NULL,
    [IsAuditEnabled]                                    BIT              CONSTRAINT [DF_OrganizationBase_IsAuditEnabled] DEFAULT ((0)) NOT NULL,
    [RecurrenceExpansionSynchCreateMax]                 INT              CONSTRAINT [DF_OrganizationBase_RecurrenceExpansionSynchCreateMax] DEFAULT ((15)) NOT NULL,
    [GoalRollupExpiryTime]                              INT              CONSTRAINT [DF_OrganizationBase_GoalRollupExpiryTime] DEFAULT ((30)) NOT NULL,
    [BaseCurrencyPrecision]                             INT              CONSTRAINT [DF_OrganizationBase_BaseCurrencyPrecision] DEFAULT ((2)) NOT NULL,
    [FiscalPeriodFormatPeriod]                          INT              CONSTRAINT [DF_OrganizationBase_FiscalPeriodFormatPeriod] DEFAULT ((1)) NULL,
    [AllowClientMessageBarAd]                           BIT              CONSTRAINT [DF_OrganizationBase_AllowClientMessageBarAd] DEFAULT ((1)) NOT NULL,
    [InitialVersion]                                    NVARCHAR (20)    NULL,
    [HashFilterKeywords]                                NVARCHAR (MAX)   NULL,
    [NextCustomObjectTypeCode]                          INT              CONSTRAINT [DF_OrganizationBase_NextCustomObjectTypeCode] DEFAULT ((10000)) NOT NULL,
    [ExpireSubscriptionsInDays]                         INT              CONSTRAINT [DF_OrganizationBase_ExpireSubscriptionsInDays] DEFAULT ((90)) NOT NULL,
    [OrgDbOrgSettings]                                  NVARCHAR (MAX)   NULL,
    [PastExpansionWindow]                               INT              CONSTRAINT [DF_OrganizationBase_PastExpansionWindow] DEFAULT ((3)) NOT NULL,
    [EnableSmartMatching]                               BIT              NULL,
    [MaxRecordsForLookupFilters]                        INT              CONSTRAINT [DF_OrganizationBase_MaxRecordsForLookupFilters] DEFAULT ((300)) NOT NULL,
    [BaseCurrencySymbol]                                NVARCHAR (4000)  CONSTRAINT [DF_OrganizationBase_BaseCurrencySymbol] DEFAULT ('$') NOT NULL,
    [ReportScriptErrors]                                INT              CONSTRAINT [DF_OrganizationBase_ReportScriptErrors] DEFAULT ((0)) NOT NULL,
    [RecurrenceExpansionJobBatchSize]                   INT              CONSTRAINT [DF_OrganizationBase_RecurrenceExpansionJobBatchSize] DEFAULT ((0)) NOT NULL,
    [FutureExpansionWindow]                             INT              CONSTRAINT [DF_OrganizationBase_FutureExpansionWindow] DEFAULT ((12)) NOT NULL,
    [GetStartedPaneContentEnabled]                      BIT              CONSTRAINT [DF_OrganizationBase_GetStartedPaneContentEnabled] DEFAULT ((1)) NOT NULL,
    [SampleDataImportId]                                UNIQUEIDENTIFIER NULL,
    [BaseISOCurrencyCode]                               NVARCHAR (4000)  CONSTRAINT [DF_OrganizationBase_BaseISOCurrencyCode] DEFAULT ('USD') NOT NULL,
    [GoalRollupFrequency]                               INT              CONSTRAINT [DF_OrganizationBase_GoalRollupFrequency] DEFAULT ((24)) NOT NULL,
    [CreatedOnBehalfBy]                                 UNIQUEIDENTIFIER NULL,
    [HashDeltaSubjectCount]                             INT              NULL,
    [HashMaxCount]                                      INT              NULL,
    [FiscalYearFormatYear]                              INT              CONSTRAINT [DF_OrganizationBase_FiscalYearFormatYear] DEFAULT ((1)) NULL,
    [FiscalYearFormatPrefix]                            INT              CONSTRAINT [DF_OrganizationBase_FiscalYearFormatPrefix] DEFAULT ((1)) NULL,
    [PinpointLanguageCode]                              INT              NULL,
    [FiscalYearFormatSuffix]                            INT              CONSTRAINT [DF_OrganizationBase_FiscalYearFormatSuffix] DEFAULT ((3)) NULL,
    [AllowUserFormModePreference]                       BIT              CONSTRAINT [DF_OrganizationBase_AllowUserFormModePreference] DEFAULT ((1)) NOT NULL,
    [MaximumActiveBusinessProcessFlowsAllowedPerEntity] INT              CONSTRAINT [DF_OrganizationBase_MaximumActiveBusinessProcessFlowsAllowedPerEntity] DEFAULT ((10)) NULL,
    [YammerGroupId]                                     INT              NULL,
    [IsUserAccessAuditEnabled]                          BIT              CONSTRAINT [DF_OrganizationBase_IsUserAccessAuditEnabled] DEFAULT ((0)) NOT NULL,
    [IsDefaultCountryCodeCheckEnabled]                  BIT              CONSTRAINT [DF_OrganizationBase_IsDefaultCountryCodeCheckEnabled] DEFAULT ((1)) NOT NULL,
    [MetadataSyncLastTimeOfNeverExpiredDeletedObjects]  DATETIME         NULL,
    [IncomingEmailExchangeEmailRetrievalBatchSize]      INT              CONSTRAINT [DF_OrganizationBase_IncomingEmailExchangeEmailRetrievalBatchSize] DEFAULT ((10)) NULL,
    [QuickFindRecordLimitEnabled]                       BIT              CONSTRAINT [DF_OrganizationBase_QuickFindRecordLimitEnabled] DEFAULT ((1)) NOT NULL,
    [YammerOAuthAccessTokenExpired]                     BIT              NULL,
    [UseSkypeProtocol]                                  BIT              CONSTRAINT [DF_OrganizationBase_UseSkypeProtocol] DEFAULT ((1)) NOT NULL,
    [DefaultEmailServerProfileId]                       UNIQUEIDENTIFIER NULL,
    [GenerateAlertsForErrors]                           BIT              CONSTRAINT [DF_OrganizationBase_GenerateAlertsForErrors] DEFAULT ((1)) NOT NULL,
    [DefaultCountryCode]                                NVARCHAR (15)    NULL,
    [EmailCorrelationEnabled]                           BIT              CONSTRAINT [DF_OrganizationBase_EmailCorrelationEnabled] DEFAULT ((1)) NOT NULL,
    [UserAccessAuditingInterval]                        INT              CONSTRAINT [DF_OrganizationBase_UserAccessAuditingInterval] DEFAULT ((4)) NOT NULL,
    [IsAutoSaveEnabled]                                 BIT              CONSTRAINT [DF_OrganizationBase_IsAutoSaveEnabled] DEFAULT ((1)) NOT NULL,
    [DefaultEmailSettings]                              NVARCHAR (MAX)   NULL,
    [MetadataSyncTimestamp]                             BIGINT           CONSTRAINT [DF_OrganizationBase_MetadataSyncTimestamp] DEFAULT ((1)) NOT NULL,
    [YammerNetworkPermalink]                            NVARCHAR (256)   NULL,
    [EmailConnectionChannel]                            INT              CONSTRAINT [DF_OrganizationBase_EmailConnectionChannel] DEFAULT ((0)) NOT NULL,
    [EntityImageId]                                     UNIQUEIDENTIFIER NULL,
    [NotifyMailboxOwnerOfEmailServerLevelAlerts]        BIT              CONSTRAINT [DF_OrganizationBase_NotifyMailboxOwnerOfEmailServerLevelAlerts] DEFAULT ((0)) NOT NULL,
    [BingMapsApiKey]                                    NVARCHAR (1024)  NULL,
    [GenerateAlertsForInformation]                      BIT              CONSTRAINT [DF_OrganizationBase_GenerateAlertsForInformation] DEFAULT ((1)) NOT NULL,
    [GenerateAlertsForWarnings]                         BIT              CONSTRAINT [DF_OrganizationBase_GenerateAlertsForWarnings] DEFAULT ((0)) NOT NULL,
    [YammerPostMethod]                                  INT              NULL,
    [AllowUsersSeeAppdownloadMessage]                   BIT              CONSTRAINT [DF_OrganizationBase_AllowUsersSeeAppdownloadMessage] DEFAULT ((1)) NOT NULL,
    [UseReadForm]                                       BIT              CONSTRAINT [DF_OrganizationBase_UseReadForm] DEFAULT ((0)) NOT NULL,
    [EnableBingMapsIntegration]                         BIT              CONSTRAINT [DF_OrganizationBase_EnableBingMapsIntegration] DEFAULT ((1)) NOT NULL,
    [SignupOutlookDownloadFWLink]                       NVARCHAR (200)   CONSTRAINT [DF_OrganizationBase_SignupOutlookDownloadFWLink] DEFAULT ('http://go.microsoft.com/fwlink/?LinkID=321806') NOT NULL,
    [DisableSocialCare]                                 BIT              CONSTRAINT [DF_OrganizationBase_DisableSocialCare] DEFAULT ((0)) NOT NULL,
    [CascadeStatusUpdate]                               BIT              CONSTRAINT [DF_OrganizationBase_CascadeStatusUpdate] DEFAULT ((0)) NULL,
    [RestrictStatusUpdate]                              BIT              CONSTRAINT [DF_OrganizationBase_RestrictStatusUpdate] DEFAULT ((0)) NULL,
    [SocialInsightsTermsAccepted]                       BIT              CONSTRAINT [DF_OrganizationBase_SocialInsightsTermsAccepted] DEFAULT ((0)) NULL,
    [SocialInsightsInstance]                            NVARCHAR (MAX)   NULL,
    [SuppressSLA]                                       BIT              CONSTRAINT [DF_OrganizationBase_SuppressSLA] DEFAULT ((0)) NOT NULL,
    [IsMailboxForcedUnlockingEnabled]                   BIT              CONSTRAINT [DF_OrganizationBase_IsMailboxForcedUnlockingEnabled] DEFAULT ((1)) NOT NULL,
    [IsEmailServerProfileContentFilteringEnabled]       BIT              CONSTRAINT [DF_OrganizationBase_IsEmailServerProfileContentFilteringEnabled] DEFAULT ((1)) NOT NULL,
    [IsMailboxInactiveBackoffEnabled]                   BIT              CONSTRAINT [DF_OrganizationBase_IsMailboxInactiveBackoffEnabled] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [cndx_PrimaryKey_Organization] PRIMARY KEY CLUSTERED ([OrganizationId] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [basecurrency_organization] FOREIGN KEY ([BaseCurrencyId]) REFERENCES [dbo].[TransactionCurrencyBase] ([TransactionCurrencyId]) NOT FOR REPLICATION,
    CONSTRAINT [calendar_organization] FOREIGN KEY ([BusinessClosureCalendarId]) REFERENCES [dbo].[CalendarBase] ([CalendarId]) NOT FOR REPLICATION,
    CONSTRAINT [EmailServerProfile_Organization] FOREIGN KEY ([DefaultEmailServerProfileId]) REFERENCES [dbo].[EmailServerProfileBase] ([EmailServerProfileId]) NOT FOR REPLICATION,
    CONSTRAINT [Template_Organization] FOREIGN KEY ([AcknowledgementTemplateId]) REFERENCES [dbo].[TemplateBaseIds] ([TemplateId]) NOT FOR REPLICATION
);


GO
EXECUTE sp_tableoption @TableNamePattern = N'[dbo].[OrganizationBase]', @OptionName = N'text in row', @OptionValue = N'7000';


GO
CREATE NONCLUSTERED INDEX [ndx_QF_Name]
    ON [dbo].[OrganizationBase]([Name] ASC) WITH (FILLFACTOR = 80);

