CREATE TABLE [dbo].[SharePointDocumentBase] (
    [CopySource]                NVARCHAR (200)   NULL,
    [FileSize]                  INT              NULL,
    [AbsoluteUrl]               NVARCHAR (200)   NULL,
    [BusinessUnitId]            UNIQUEIDENTIFIER NULL,
    [AppModifiedBy]             NVARCHAR (200)   NULL,
    [Author]                    NVARCHAR (2000)  NULL,
    [Edit]                      NVARCHAR (200)   NULL,
    [TransactionCurrencyId]     UNIQUEIDENTIFIER NULL,
    [Title]                     NVARCHAR (2000)  NULL,
    [SharePointCreatedOn]       DATETIME         NULL,
    [CheckInComment]            NVARCHAR (200)   NULL,
    [EditUrl]                   NVARCHAR (200)   NULL,
    [ContentType]               NVARCHAR (200)   NULL,
    [ModifiedOn]                DATETIME         NULL,
    [DocumentId]                INT              NULL,
    [AppCreatedBy]              NVARCHAR (200)   NULL,
    [RelativeLocation]          NVARCHAR (200)   NULL,
    [CreatedOn]                 DATETIME         NULL,
    [CreatedBy]                 UNIQUEIDENTIFIER NULL,
    [CreatedOnBehalfBy]         UNIQUEIDENTIFIER NULL,
    [OrganizationId]            UNIQUEIDENTIFIER NOT NULL,
    [CheckedOutTo]              NVARCHAR (200)   NULL,
    [Version]                   NVARCHAR (200)   NULL,
    [ModifiedBy]                UNIQUEIDENTIFIER NULL,
    [OwningBusinessUnit]        UNIQUEIDENTIFIER NULL,
    [IsCheckedOut]              BIT              CONSTRAINT [DF_SharePointDocumentBase_IsCheckedOut] DEFAULT ((0)) NULL,
    [ChildFolderCount]          INT              NULL,
    [ContentTypeId]             INT              NULL,
    [FileType]                  NVARCHAR (200)   NULL,
    [ExchangeRate]              DECIMAL (23, 10) NULL,
    [OwnerId]                   UNIQUEIDENTIFIER CONSTRAINT [DF_SharePointDocumentBase_OwnerId] DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [ReadUrl]                   NVARCHAR (200)   NULL,
    [ModifiedOnBehalfBy]        UNIQUEIDENTIFIER NULL,
    [FullName]                  NVARCHAR (160)   NULL,
    [SharePointDocumentId]      UNIQUEIDENTIFIER NOT NULL,
    [LocationId]                NVARCHAR (2000)  NULL,
    [ChildItemCount]            INT              NULL,
    [Modified]                  DATETIME         NULL,
    [SharePointModifiedBy]      NVARCHAR (200)   NULL,
    [IsFolder]                  BIT              CONSTRAINT [DF_SharePointDocumentBase_IsFolder] DEFAULT ((0)) NULL,
    [RegardingObjectId]         UNIQUEIDENTIFIER NULL,
    [RegardingObjectIdName]     NVARCHAR (4000)  NULL,
    [RegardingObjectTypeCode]   INT              NULL,
    [OwnerIdType]               INT              CONSTRAINT [DF_SharePointDocumentBase_OwnerIdType] DEFAULT ((8)) NOT NULL,
    [RegardingObjectIdYomiName] NVARCHAR (4000)  NULL,
    CONSTRAINT [ndx_PrimaryKey_SharePointDocument] PRIMARY KEY CLUSTERED ([SharePointDocumentId] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [business_unit_sharepointdocument] FOREIGN KEY ([OwningBusinessUnit]) REFERENCES [dbo].[BusinessUnitBase] ([BusinessUnitId]) NOT FOR REPLICATION,
    CONSTRAINT [business_unit_sharepointdocument2] FOREIGN KEY ([BusinessUnitId]) REFERENCES [dbo].[BusinessUnitBase] ([BusinessUnitId]) NOT FOR REPLICATION,
    CONSTRAINT [owner_sharepointdocument] FOREIGN KEY ([OwnerId]) REFERENCES [dbo].[OwnerBase] ([OwnerId]) NOT FOR REPLICATION,
    CONSTRAINT [TransactionCurrency_SharePointDocument] FOREIGN KEY ([TransactionCurrencyId]) REFERENCES [dbo].[TransactionCurrencyBase] ([TransactionCurrencyId]) NOT FOR REPLICATION
);


GO
CREATE NONCLUSTERED INDEX [ndx_QuickFind_SharePointDocument]
    ON [dbo].[SharePointDocumentBase]([LocationId] ASC) WITH (FILLFACTOR = 80);

