CREATE TABLE [dbo].[UserSettingsBase] (
    [SystemUserId]                               UNIQUEIDENTIFIER NOT NULL,
    [BusinessUnitId]                             UNIQUEIDENTIFIER NOT NULL,
    [HomepageArea]                               NVARCHAR (200)   NULL,
    [PagingLimit]                                INT              NULL,
    [HomepageSubarea]                            NVARCHAR (200)   NULL,
    [DefaultCalendarView]                        INT              NULL,
    [WorkdayStartTime]                           NVARCHAR (5)     NULL,
    [WorkdayStopTime]                            NVARCHAR (5)     NULL,
    [IgnoreUnsolicitedEmail]                     BIT              CONSTRAINT [DF_UserSettingsBase_IgnoreUnsolicitedEmail] DEFAULT ((1)) NOT NULL,
    [TimeZoneBias]                               INT              CONSTRAINT [Set_To_Zero167] DEFAULT ((0)) NOT NULL,
    [TimeZoneStandardBias]                       INT              CONSTRAINT [Set_To_Zero168] DEFAULT ((0)) NOT NULL,
    [TimeZoneDaylightBias]                       INT              CONSTRAINT [Set_To_Zero169] DEFAULT ((0)) NOT NULL,
    [TimeZoneCode]                               SMALLINT         CONSTRAINT [Set_To_Zero170] DEFAULT ((0)) NOT NULL,
    [TimeZoneStandardYear]                       SMALLINT         CONSTRAINT [Set_To_Zero171] DEFAULT ((0)) NOT NULL,
    [TimeZoneStandardMonth]                      SMALLINT         CONSTRAINT [Set_To_Zero172] DEFAULT ((0)) NOT NULL,
    [TimeZoneStandardDay]                        SMALLINT         CONSTRAINT [Set_To_Zero173] DEFAULT ((0)) NOT NULL,
    [TimeZoneStandardDayOfWeek]                  SMALLINT         CONSTRAINT [Set_To_Zero174] DEFAULT ((0)) NOT NULL,
    [TimeZoneStandardHour]                       SMALLINT         CONSTRAINT [Set_To_Zero175] DEFAULT ((0)) NOT NULL,
    [TimeZoneStandardMinute]                     SMALLINT         CONSTRAINT [Set_To_Zero176] DEFAULT ((0)) NOT NULL,
    [TimeZoneStandardSecond]                     SMALLINT         CONSTRAINT [Set_To_Zero177] DEFAULT ((0)) NOT NULL,
    [TimeZoneDaylightYear]                       SMALLINT         CONSTRAINT [Set_To_Zero178] DEFAULT ((0)) NOT NULL,
    [TimeZoneDaylightMonth]                      SMALLINT         CONSTRAINT [Set_To_Zero179] DEFAULT ((0)) NOT NULL,
    [TimeZoneDaylightDay]                        SMALLINT         CONSTRAINT [Set_To_Zero180] DEFAULT ((0)) NOT NULL,
    [TimeZoneDaylightDayOfWeek]                  SMALLINT         CONSTRAINT [Set_To_Zero181] DEFAULT ((0)) NOT NULL,
    [TimeZoneDaylightHour]                       SMALLINT         CONSTRAINT [Set_To_Zero182] DEFAULT ((0)) NOT NULL,
    [TimeZoneDaylightMinute]                     SMALLINT         CONSTRAINT [Set_To_Zero183] DEFAULT ((0)) NOT NULL,
    [TimeZoneDaylightSecond]                     SMALLINT         CONSTRAINT [Set_To_Zero184] DEFAULT ((0)) NOT NULL,
    [ModifiedBy]                                 UNIQUEIDENTIFIER NULL,
    [AdvancedFindStartupMode]                    SMALLINT         CONSTRAINT [DF_UserSettingsBase_AdvancedFindStartupMode] DEFAULT ((1)) NOT NULL,
    [CreatedOn]                                  DATETIME         NULL,
    [TrackingTokenId]                            INT              NULL,
    [NextTrackingNumber]                         INT              NULL,
    [ModifiedOn]                                 DATETIME         NULL,
    [CreatedBy]                                  UNIQUEIDENTIFIER NULL,
    [VersionNumber]                              ROWVERSION       NULL,
    [UserProfile]                                NVARCHAR (1024)  NULL,
    [NumberSeparator]                            NVARCHAR (5)     CONSTRAINT [DF_UserSettingsBase_NumberSeparator] DEFAULT (',') NOT NULL,
    [OutlookSyncInterval]                        INT              CONSTRAINT [DF_UserSettingsBase_OutlookSyncInterval] DEFAULT ((900000)) NOT NULL,
    [UseCrmFormForTask]                          BIT              CONSTRAINT [DF_UserSettingsBase_UseCrmFormForTask] DEFAULT ((1)) NOT NULL,
    [PricingDecimalPrecision]                    INT              CONSTRAINT [DF_UserSettingsBase_PricingDecimalPrecision] DEFAULT ((2)) NULL,
    [SyncContactCompany]                         BIT              CONSTRAINT [DF_UserSettingsBase_SyncContactCompany] DEFAULT ((1)) NOT NULL,
    [DateSeparator]                              NVARCHAR (5)     CONSTRAINT [DF_UserSettingsBase_DateSeparator] DEFAULT ('/') NOT NULL,
    [LongDateFormatCode]                         INT              CONSTRAINT [DF_UserSettingsBase_LongDateFormatCode] DEFAULT ((0)) NOT NULL,
    [AllowEmailCredentials]                      BIT              CONSTRAINT [DF_UserSettingsBase_AllowEmailCredentials] DEFAULT ((0)) NOT NULL,
    [FullNameConventionCode]                     INT              CONSTRAINT [DF_UserSettingsBase_FullNameConventionCode] DEFAULT ((0)) NOT NULL,
    [TimeSeparator]                              NVARCHAR (5)     NULL,
    [TimeFormatCode]                             INT              CONSTRAINT [DF_UserSettingsBase_TimeFormatCode] DEFAULT ((0)) NOT NULL,
    [NegativeFormatCode]                         INT              CONSTRAINT [DF_UserSettingsBase_NegativeFormatCode] DEFAULT ((0)) NOT NULL,
    [OfflineSyncInterval]                        INT              CONSTRAINT [DF_UserSettingsBase_OfflineSyncInterval] DEFAULT ((900000)) NOT NULL,
    [CalendarType]                               INT              CONSTRAINT [DF_UserSettingsBase_CalendarType] DEFAULT ((2)) NOT NULL,
    [CurrencySymbol]                             NVARCHAR (13)    CONSTRAINT [DF_UserSettingsBase_CurrencySymbol] DEFAULT ('$') NOT NULL,
    [TransactionCurrencyId]                      UNIQUEIDENTIFIER NULL,
    [UILanguageId]                               INT              CONSTRAINT [DF_UserSettingsBase_UILanguageId] DEFAULT ((0)) NOT NULL,
    [UseCrmFormForContact]                       BIT              CONSTRAINT [DF_UserSettingsBase_UseCrmFormForContact] DEFAULT ((1)) NOT NULL,
    [CurrencyFormatCode]                         INT              CONSTRAINT [DF_UserSettingsBase_CurrencyFormatCode] DEFAULT ((0)) NOT NULL,
    [AddressBookSyncInterval]                    INT              CONSTRAINT [DF_UserSettingsBase_AddressBookSyncInterval] DEFAULT ((86400000)) NOT NULL,
    [DecimalSymbol]                              NVARCHAR (5)     CONSTRAINT [DF_UserSettingsBase_DecimalSymbol] DEFAULT ('.') NOT NULL,
    [UseCrmFormForEmail]                         BIT              CONSTRAINT [DF_UserSettingsBase_UseCrmFormForEmail] DEFAULT ((0)) NOT NULL,
    [ShowWeekNumber]                             BIT              CONSTRAINT [DF_UserSettingsBase_ShowWeekNumber] DEFAULT ((0)) NOT NULL,
    [NegativeCurrencyFormatCode]                 INT              CONSTRAINT [DF_UserSettingsBase_NegativeCurrencyFormatCode] DEFAULT ((0)) NOT NULL,
    [TimeFormatString]                           NVARCHAR (255)   NULL,
    [EmailUsername]                              NVARCHAR (200)   NULL,
    [DateFormatString]                           NVARCHAR (255)   NULL,
    [ReportScriptErrors]                         INT              CONSTRAINT [DF_UserSettingsBase_ReportScriptErrors] DEFAULT ((1)) NOT NULL,
    [UseImageStrips]                             BIT              CONSTRAINT [DF_UserSettingsBase_UseImageStrips] DEFAULT ((1)) NOT NULL,
    [EmailPassword]                              NVARCHAR (200)   NULL,
    [DateFormatCode]                             INT              CONSTRAINT [DF_UserSettingsBase_DateFormatCode] DEFAULT ((0)) NOT NULL,
    [UseCrmFormForAppointment]                   BIT              CONSTRAINT [DF_UserSettingsBase_UseCrmFormForAppointment] DEFAULT ((0)) NOT NULL,
    [IsDuplicateDetectionEnabledWhenGoingOnline] BIT              CONSTRAINT [DF_UserSettingsBase_IsDuplicateDetectionEnabledWhenGoingOnline] DEFAULT ((0)) NOT NULL,
    [LocaleId]                                   INT              NULL,
    [IncomingEmailFilteringMethod]               INT              CONSTRAINT [DF_UserSettingsBase_IncomingEmailFilteringMethod] DEFAULT ((2)) NOT NULL,
    [CurrencyDecimalPrecision]                   INT              CONSTRAINT [DF_UserSettingsBase_CurrencyDecimalPrecision] DEFAULT ((2)) NULL,
    [AMDesignator]                               NVARCHAR (25)    CONSTRAINT [DF_UserSettingsBase_AMDesignator] DEFAULT ('AM') NOT NULL,
    [NumberGroupFormat]                          NVARCHAR (25)    NULL,
    [HelpLanguageId]                             INT              NULL,
    [PMDesignator]                               NVARCHAR (25)    CONSTRAINT [DF_UserSettingsBase_PMDesignator] DEFAULT ('PM') NOT NULL,
    [CreatedOnBehalfBy]                          UNIQUEIDENTIFIER NULL,
    [GetStartedPaneContentEnabled]               BIT              CONSTRAINT [DF_UserSettingsBase_GetStartedPaneContentEnabled] DEFAULT ((1)) NOT NULL,
    [AutoCreateContactOnPromote]                 SMALLINT         CONSTRAINT [DF_UserSettingsBase_AutoCreateContactOnPromote] DEFAULT ((1)) NOT NULL,
    [ModifiedOnBehalfBy]                         UNIQUEIDENTIFIER NULL,
    [PersonalizationSettings]                    NVARCHAR (MAX)   NULL,
    [VisualizationPaneLayout]                    INT              CONSTRAINT [DF_UserSettingsBase_VisualizationPaneLayout] DEFAULT ((1)) NOT NULL,
    [DataValidationModeForExportToExcel]         INT              CONSTRAINT [DF_UserSettingsBase_DataValidationModeForExportToExcel] DEFAULT ((0)) NOT NULL,
    [HomepageLayout]                             NVARCHAR (1000)  NULL,
    [IsSendAsAllowed]                            BIT              CONSTRAINT [DF_UserSettingsBase_IsSendAsAllowed] DEFAULT ((0)) NOT NULL,
    [DefaultDashboardId]                         UNIQUEIDENTIFIER NULL,
    [EntityFormMode]                             INT              CONSTRAINT [DF_UserSettingsBase_EntityFormMode] DEFAULT ((0)) NOT NULL,
    [LastAlertsViewedTime]                       DATETIME         CONSTRAINT [DF_UserSettingsBase_LastAlertsViewedTime] DEFAULT ((0)) NULL,
    [IsDefaultCountryCodeCheckEnabled]           BIT              CONSTRAINT [DF_UserSettingsBase_IsDefaultCountryCodeCheckEnabled] DEFAULT ((0)) NOT NULL,
    [DefaultCountryCode]                         NVARCHAR (15)    NULL,
    CONSTRAINT [cndx_PrimaryKey_UserSettings] PRIMARY KEY CLUSTERED ([SystemUserId] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [business_unit_user_settings] FOREIGN KEY ([BusinessUnitId]) REFERENCES [dbo].[BusinessUnitBase] ([BusinessUnitId]) NOT FOR REPLICATION,
    CONSTRAINT [transactioncurrency_usersettings] FOREIGN KEY ([TransactionCurrencyId]) REFERENCES [dbo].[TransactionCurrencyBase] ([TransactionCurrencyId]) NOT FOR REPLICATION,
    CONSTRAINT [user_settings] FOREIGN KEY ([SystemUserId]) REFERENCES [dbo].[SystemUserBase] ([SystemUserId]) NOT FOR REPLICATION,
    CONSTRAINT [AK1_UserSettingsBase_TrackingTokenId] UNIQUE NONCLUSTERED ([TrackingTokenId] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [fndx_Sync_VersionNumber]
    ON [dbo].[UserSettingsBase]([VersionNumber] ASC) WHERE ([VersionNumber] IS NOT NULL) WITH (FILLFACTOR = 80);


GO
CREATE NONCLUSTERED INDEX [ndx_Security]
    ON [dbo].[UserSettingsBase]([BusinessUnitId] ASC) WITH (FILLFACTOR = 80);

