CREATE ROLE [CRMReaderRole]
    AUTHORIZATION [dbo];


GO
ALTER ROLE [CRMReaderRole] ADD MEMBER [CRM\PrivReportingGroup {8a0aa7db-84c3-4ddf-bdca-6fbc8b5e12c6}];


GO
ALTER ROLE [CRMReaderRole] ADD MEMBER [NT AUTHORITY\NETWORK SERVICE];

