(window.bundleExecutionMarkers=window.bundleExecutionMarkers||{})["scripts/es5/officewaffleplaceholder.js?v=1.4.9962-v91onpremise"]={begin:performance.now()},(window.__wpJsonpUci=window.__wpJsonpUci||[]).push([[93],{hEjd:function(e,t,r){"use strict";t.a=r.p+"resources/images/OfficeWaffle.svg?v=1.4.9962-v91onpremise"},hp1u:function(e,t,r){"use strict";r.d(t,"b",(function(){return p})),r.d(t,"a",(function(){return O}));var n=r("c/eZ"),c=r("nuS9"),o=r("uTTW"),i=r("S6oQ"),a=r("4E+q"),s=r("c56u"),u=r("JlqV"),l=r("EGsq"),f=r("EXRB"),b=r("7EJx"),d=r("s5BY");var w=r("kyRo"),v=r("XFxG"),h=r("8ul+"),g=r("qC0c"),j=r("cZkS");
/**
 * @license Copyright (c) Microsoft Corporation. All rights reserved.
 */
function p(e){return c.createElement(m,{imgSrc:e.source,render:function(t){return c.createElement(i.a,Object(n.__assign)({focusable:"false"},e,{source:t,altText:e.altText}))}})}function O(e){return c.createElement(m,{imgSrc:e.source,render:function(t){return c.createElement(o.a,Object(n.__assign)({},e,{source:t,altText:e.altText}))}})}function m(e){var t,r=e.imgSrc,n=e.render,o=c.useContext(w.a).AssetLoader,i=c.useState(r),p=i[0],O=i[1],m=function(e,t){return Object(a.d)((function(r){
/**
 * @license Copyright (c) Microsoft Corporation. All rights reserved.
 */return function(e,t,r){var n=Object(s.w)(e),c=!Object(u.b)(e),o=Object(l.t)(e),i=Object(f.d)(e);return(n&&c||i)&&function(e,t,r){void 0===t&&(t="");var n="$webresource:",c="/webresources/",o=t.toLowerCase();return o.startsWith(n)?(r(t.substr(n.length)),!0):o.startsWith(c)?(r(t.substr(c.length)),!0):!!o.startsWith(e)&&(r(t.substr(e.length)),!0)}(o,t,r)}(r,e,t)}))}(r,(function(e){return t=e})),E=function(e){return Object(a.d)((function(t){return function(e,t){var r;if((null===(r=Object(b.w)(e))||void 0===r?void 0:r.usePathBasedUrls)&&t.toLowerCase().startsWith("/webresources/"))return Object(d.a)(e,t)}(t,e)}))}(r),_=Object(a.d)((function(e){return Object(g.b)(e,j.b)})),x=Object(a.d)(h.a);return c.useEffect((function(){m?o.loadOfflineWebResource(t).then((function(e){e&&O(v.a.createDataUri(v.b.Svg,e).toString())})):O(E||r)}),[m,E,r,t,o]),n(p,_&&x)}},mTVg:function(e,t,r){"use strict";r.d(t,"a",(function(){return a}));var n=r("c/eZ"),c=r("nuS9"),o=r("TCzx"),i=r("hp1u");
/**
 * @license Copyright (c) Microsoft Corporation. All rights reserved.
 */
function a(e){var t=e.source,r=e.style;if(o.a.getInstance().get_IsBrowserIE()&&!e.useImgInIE||e.highContrast){var a=Object(n.__assign)(Object(n.__assign)(Object(n.__assign)({},r),e.invert?{fill:"white"}:{}),e.highContrast?{fill:"windowText"}:{});return c.createElement(i.b,{source:t,style:a,fallbackToImage:!0,title:e.title,role:e.role,altText:e.altText})}var s=Object(n.__assign)(Object(n.__assign)({},r),e.invert?{filter:"invert(100%)"}:{});return c.createElement(i.a,{source:t,style:s,title:e.title,role:e.role,altText:e.altText})}},rjnX:function(e,t,r){"use strict";r.r(t),r.d(t,"OfficeWafflePlaceholder",(function(){return B}));var n=r("c/eZ"),c=r("nuS9"),o=r("4E+q"),i=r("evW+"),a=r("YWpA"),s=r("lU69"),u=r("H/hG"),l=r("7cIM"),f=r("wV3W"),b=r("EGsq"),d=r("Ww2r"),w=r("I0a0"),v=r("VnpK"),h=r("mTVg"),g=r("hEjd"),j=r("Zh8V"),p=r("9rQ4"),O=r("vO+w"),m={color:"#FFF",fontSize:"16px",width:"100%",textAlign:"center"},E={width:"1.143rem",height:"1.286rem"},_=Object(s.a)(),x=["Web.NavBar.AppSwitcher_Caption"],C=function(e){return Object(O.b)(e)?Object(O.a)(e):null};function T(e){if(e.keyCode===p.a.Escape){var t=document.getElementById(_);t&&t.focus()}}function k(e,t){var r=t?t.Components.AppHeader.BackgroundColor:e.colors.NavBar.NavBar1.Fill,n=t?t.Components.AppHeader.Hover.BackgroundColor:e.colors.NavBar.NavBar2.Fill;return Object(j.e)({cursor:"pointer",borderWidth:0,backgroundColor:r,width:e.sizes.NavbarHeight,height:e.sizes.NavbarHeight,display:"flex",alignItems:"center",justifyContent:"center",":focus":Object(j.d)(e,t)},n)}var B=c.memo((function(){var e=Object(o.d)(f.a),t=Object(o.d)(C),r=Object(o.d)(b.D),s=Object(w.a)(x),j=Object(d.c)(s,"Web.NavBar.AppSwitcher_Caption"),p=Object(o.d)(v.n),O=Object(o.c)();return c.createElement(a.a,{onKeyDown:T},c.createElement(i.a,{key:"button",id:_,testhooks:{id:"officewaffleplaceholder"},style:k(e,t),title:j,accessibilityLabel:j,onClick:function(){return O(Object(l.a)(r||"https://go.microsoft.com/fwlink/?LinkID=246804"))}},function(e){var t=Object(n.__assign)(Object(n.__assign)({},m),E),r=c.createElement(h.a,{source:g.a,style:E,highContrast:e,invert:!0});return c.createElement(u.a,{style:t},r)}(p)))}))}}]),window.bundleExecutionMarkers["scripts/es5/officewaffleplaceholder.js?v=1.4.9962-v91onpremise"].end=window.performance.now(),window.reportBundleExecutionTimes&&window.reportBundleExecutionTimes();