CREATE TABLE [MetadataSchema].[Entity] (
    [EntityId]                            UNIQUEIDENTIFIER ROWGUIDCOL NOT NULL,
    [Name]                                NVARCHAR (64)    NULL,
    [ObjectTypeCode]                      INT              CONSTRAINT [Set_To_Zero7] DEFAULT ((0)) NULL,
    [PhysicalName]                        NVARCHAR (64)    NULL,
    [LogicalName]                         NVARCHAR (64)    NULL,
    [CollectionName]                      NVARCHAR (64)    NULL,
    [BaseTableName]                       NVARCHAR (64)    NULL,
    [LogicalCollectionName]               NVARCHAR (64)    NULL,
    [IsIntersect]                         BIT              NOT NULL,
    [IsSecurityIntersect]                 BIT              NOT NULL,
    [IsLookupTable]                       BIT              NOT NULL,
    [EventMask]                           INT              NOT NULL,
    [IsLogicalEntity]                     BIT              CONSTRAINT [Set_To_Zero8] DEFAULT ((0)) NULL,
    [IsCustomizable]                      BIT              CONSTRAINT [Set_To_Zero9] DEFAULT ((0)) NULL,
    [IsCollaboration]                     BIT              CONSTRAINT [Set_To_Zero10] DEFAULT ((0)) NULL,
    [IsActivity]                          BIT              CONSTRAINT [Set_To_Zero11] DEFAULT ((0)) NULL,
    [AddressTableName]                    NVARCHAR (64)    NULL,
    [IsMappable]                          BIT              CONSTRAINT [Set_To_Zero12] DEFAULT ((0)) NULL,
    [OwnershipTypeMask]                   INT              CONSTRAINT [Set_To_Zero13] DEFAULT ((0)) NOT NULL,
    [IsAudited]                           BIT              CONSTRAINT [Set_To_Zero14] DEFAULT ((0)) NOT NULL,
    [UsesFullnameConventionRules]         BIT              CONSTRAINT [Set_To_Zero15] DEFAULT ((0)) NOT NULL,
    [IsParented]                          BIT              CONSTRAINT [Set_To_Zero16] DEFAULT ((0)) NOT NULL,
    [EntityMask]                          INT              CONSTRAINT [Set_To_Zero17] DEFAULT ((0)) NULL,
    [IsReplicated]                        BIT              CONSTRAINT [Set_To_Zero_2B_Repl_0] DEFAULT ((0)) NOT NULL,
    [IsReplicationUserFiltered]           BIT              CONSTRAINT [Set_To_Zero_2B_Repl_2] DEFAULT ((0)) NOT NULL,
    [IsChildEntity]                       BIT              CONSTRAINT [Set_To_Zero_ChildEntity] DEFAULT ((0)) NOT NULL,
    [IsCustomEntity]                      BIT              DEFAULT ((0)) NOT NULL,
    [IsActivityParty]                     BIT              CONSTRAINT [Set_To_Zero_ActivityParty] DEFAULT ((0)) NOT NULL,
    [IsValidForAdvancedFind]              BIT              CONSTRAINT [Set_To_Zero_Entity_IsValidForAdvancedFind] DEFAULT ((0)) NOT NULL,
    [ExtensionTableName]                  NVARCHAR (64)    NULL,
    [VersionNumber]                       ROWVERSION       NOT NULL,
    [ReportViewName]                      NVARCHAR (64)    NULL,
    [IsRequiredOffline]                   BIT              DEFAULT ((0)) NOT NULL,
    [IsRenameable]                        BIT              DEFAULT ((0)) NOT NULL,
    [EntityClassName]                     NVARCHAR (255)   DEFAULT ('') NOT NULL,
    [ServiceClassName]                    NVARCHAR (255)   DEFAULT ('') NOT NULL,
    [EntityAssembly]                      NVARCHAR (255)   DEFAULT ('') NOT NULL,
    [ServiceAssembly]                     NVARCHAR (255)   DEFAULT ('') NOT NULL,
    [EntityRowId]                         UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    [IsDuplicateCheckSupported]           BIT              DEFAULT ((0)) NOT NULL,
    [IsImportable]                        BIT              DEFAULT ((0)) NOT NULL,
    [IsShareableAcrossOrgs]               BIT              DEFAULT ((0)) NOT NULL,
    [IsPublishable]                       BIT              DEFAULT ((0)) NOT NULL,
    [OriginalLocalizedName]               NVARCHAR (100)   NULL,
    [OriginalLocalizedCollectionName]     NVARCHAR (100)   NULL,
    [CanTriggerWorkflow]                  BIT              DEFAULT ((0)) NOT NULL,
    [WorkflowSupport]                     INT              DEFAULT ((0)) NOT NULL,
    [CanBeChildInCustomRelationship]      BIT              DEFAULT ((0)) NOT NULL,
    [CanBeInCustomEntityAssociation]      BIT              DEFAULT ((0)) NOT NULL,
    [CanBeInCustomReflexiveRelationship]  BIT              DEFAULT ((0)) NOT NULL,
    [IsMailMergeEnabled]                  BIT              DEFAULT ((0)) NOT NULL,
    [RecurrenceTypeMask]                  INT              DEFAULT ((0)) NOT NULL,
    [RecurrenceBaseEntityId]              UNIQUEIDENTIFIER NULL,
    [IsDocumentManagementEnabled]         BIT              DEFAULT ((0)) NOT NULL,
    [MobileAccessLevelMask]               INT              DEFAULT ((0)) NOT NULL,
    [IsVisibleInMobile]                   BIT              DEFAULT ((0)) NOT NULL,
    [IsMultipleQueueEnabled]              BIT              DEFAULT ((0)) NOT NULL,
    [AutoRouteToOwnerQueue]               BIT              DEFAULT ((0)) NOT NULL,
    [IsAuditEnabled]                      BIT              DEFAULT ((0)) NOT NULL,
    [IsConnectionsEnabled]                BIT              DEFAULT ((0)) NOT NULL,
    [IsReadingPaneEnabled]                BIT              DEFAULT ((1)) NOT NULL,
    [IsMapiGridEnabled]                   BIT              DEFAULT ((1)) NOT NULL,
    [IsEnabledForCharts]                  BIT              DEFAULT ((1)) NOT NULL,
    [IconLargeName]                       NVARCHAR (512)   NULL,
    [IconMediumName]                      NVARCHAR (512)   NULL,
    [IconSmallName]                       NVARCHAR (512)   NULL,
    [NextCustomAttributeColumnNumber]     INT              DEFAULT ((1)) NOT NULL,
    [ActivityTypeMask]                    INT              DEFAULT ((0)) NOT NULL,
    [IsSolutionAware]                     BIT              DEFAULT ((0)) NOT NULL,
    [SolutionId]                          UNIQUEIDENTIFIER DEFAULT ('fd140aad-4df4-11dd-bd17-0019b9312238') NOT NULL,
    [SupportingSolutionId]                UNIQUEIDENTIFIER DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    [ComponentState]                      TINYINT          DEFAULT ((0)) NOT NULL,
    [OverwriteTime]                       DATETIME         DEFAULT ((0)) NOT NULL,
    [InheritsFrom]                        UNIQUEIDENTIFIER NULL,
    [IsInheritedFrom]                     BIT              DEFAULT ((0)) NOT NULL,
    [CanBeSecured]                        BIT              CONSTRAINT [DF_Entity_CanBeSecured] DEFAULT ((0)) NOT NULL,
    [CanModifyConnectionSettings]         BIT              CONSTRAINT [DF_Entity_CanModifyConnectionSettings] DEFAULT ((1)) NOT NULL,
    [CanModifyDuplicateDetectionSettings] BIT              CONSTRAINT [DF_Entity_CanModifyDuplicateDetectionSettings] DEFAULT ((1)) NOT NULL,
    [CanModifyMailMergeSettings]          BIT              CONSTRAINT [DF_Entity_CanModifyMailMergeSettings] DEFAULT ((1)) NOT NULL,
    [CanModifyQueueSettings]              BIT              CONSTRAINT [DF_Entity_CanModifyQueueSettings] DEFAULT ((1)) NOT NULL,
    [CanCreateAttributes]                 BIT              CONSTRAINT [DF_Entity_CanCreateAttributes] DEFAULT ((1)) NOT NULL,
    [CanBeRelatedEntityInRelationship]    BIT              CONSTRAINT [DF_Entity_CanBeRelatedEntityInRelationship] DEFAULT ((1)) NOT NULL,
    [CanBePrimaryEntityInRelationship]    BIT              CONSTRAINT [DF_Entity_CanBePrimaryEntityInRelationship] DEFAULT ((1)) NOT NULL,
    [CanBeInManyToMany]                   BIT              CONSTRAINT [DF_Entity_CanBeInManyToMany] DEFAULT ((1)) NOT NULL,
    [CanCreateForms]                      BIT              CONSTRAINT [DF_Entity_CanCreateForms] DEFAULT ((1)) NOT NULL,
    [CanCreateCharts]                     BIT              CONSTRAINT [DF_Entity_CanCreateCharts] DEFAULT ((1)) NOT NULL,
    [CanCreateViews]                      BIT              CONSTRAINT [DF_Entity_CanCreateViews] DEFAULT ((1)) NOT NULL,
    [CanModifyAuditSettings]              BIT              CONSTRAINT [DF_Entity_CanModifyAuditSettings] DEFAULT ((1)) NOT NULL,
    [CanModifyMobileVisibility]           BIT              CONSTRAINT [DF_Entity_CanModifyMobileVisibility] DEFAULT ((0)) NOT NULL,
    [ParentComponentType]                 INT              NULL,
    [ParentControllingAttributeName]      NVARCHAR (100)   NULL,
    [IsManaged]                           BIT              DEFAULT ((0)) NOT NULL,
    [CanModifyAdditionalSettings]         BIT              CONSTRAINT [DF_Entity_CanModifyAdditionalSettings] DEFAULT ((1)) NOT NULL,
    [IsAIRUpdated]                        BIT              DEFAULT ((0)) NOT NULL,
    [IsQuickCreateEnabled]                BIT              DEFAULT ((0)) NOT NULL,
    [IntroducedVersion]                   NVARCHAR (48)    NULL,
    [AutoCreateAccessTeams]               BIT              DEFAULT ((0)) NOT NULL,
    [IsBusinessProcessEnabled]            BIT              DEFAULT ((0)) NOT NULL,
    [HasIdsTable]                         BIT              DEFAULT ((0)) NOT NULL,
    [IsReadOnlyInMobileClient]            BIT              DEFAULT ((0)) NOT NULL,
    [IsVisibleInMobileClient]             BIT              DEFAULT ((0)) NOT NULL,
    [CanModifyMobileClientVisibility]     BIT              CONSTRAINT [DF_Entity_CanModifyMobileClientVisibility] DEFAULT ((1)) NOT NULL,
    [CanModifyMobileClientReadOnly]       BIT              CONSTRAINT [DF_Entity_CanModifyMobileClientReadOnly] DEFAULT ((1)) NOT NULL,
    [IsEnabledForTrace]                   BIT              DEFAULT ((0)) NOT NULL,
    [IsStateModelAware]                   BIT              DEFAULT ((0)) NOT NULL,
    [EnforceStateTransitions]             BIT              DEFAULT ((0)) NOT NULL,
    CONSTRAINT [XPKEntity] PRIMARY KEY CLUSTERED ([EntityId] ASC, [SolutionId] ASC, [ComponentState] ASC, [OverwriteTime] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ndx_entity_logicalname]
    ON [MetadataSchema].[Entity]([LogicalName] ASC);


GO
CREATE NONCLUSTERED INDEX [ndx_entity_name]
    ON [MetadataSchema].[Entity]([Name] ASC);


GO
CREATE NONCLUSTERED INDEX [ndx_entity_physicalname]
    ON [MetadataSchema].[Entity]([PhysicalName] ASC);

