CREATE TABLE [dbo].[AdvancedSimilarityRuleBase] (
    [CreatedOn]                       DATETIME         NULL,
    [ModifiedOn]                      DATETIME         NULL,
    [CreatedOnBehalfBy]               UNIQUEIDENTIFIER NULL,
    [ModifiedBy]                      UNIQUEIDENTIFIER NULL,
    [FetchXmlList]                    NVARCHAR (MAX)   NULL,
    [SourceEntity]                    INT              NULL,
    [FilterResultByStatus]            INT              NULL,
    [IsManaged]                       BIT              CONSTRAINT [DF_AdvancedSimilarityRuleBase_IsManaged] DEFAULT ((0)) NOT NULL,
    [CreatedBy]                       UNIQUEIDENTIFIER NULL,
    [ModifiedOnBehalfBy]              UNIQUEIDENTIFIER NULL,
    [OrganizationId]                  UNIQUEIDENTIFIER NOT NULL,
    [name]                            NVARCHAR (100)   NULL,
    [Description]                     NVARCHAR (MAX)   NULL,
    [IsAzureMLRequired]               BIT              NULL,
    [OverwriteTime]                   DATETIME         CONSTRAINT [DF_AdvancedSimilarityRuleBase_OverwriteTime] DEFAULT ((0)) NOT NULL,
    [NgramSize]                       INT              NULL,
    [MaxNumberKeyphrases]             INT              NULL,
    [SolutionId]                      UNIQUEIDENTIFIER CONSTRAINT [DF_AdvancedSimilarityRuleBase_SolutionId] DEFAULT ('fd140aad-4df4-11dd-bd17-0019b9312238') NOT NULL,
    [AdvancedSimilarityRuleId]        UNIQUEIDENTIFIER NOT NULL,
    [StateCode]                       INT              NOT NULL,
    [ExactMatchList]                  NVARCHAR (MAX)   NULL,
    [FilterResultByStatusDisplayName] NVARCHAR (50)    NULL,
    [SupportingSolutionId]            UNIQUEIDENTIFIER NULL,
    [ComponentState]                  INT              CONSTRAINT [DF_AdvancedSimilarityRuleBase_ComponentState] DEFAULT ((0)) NOT NULL,
    [StatusCode]                      INT              NULL,
    [AdvancedSimilarityRuleIdUnique]  UNIQUEIDENTIFIER CONSTRAINT [DF_AdvancedSimilarityRuleBase_AdvancedSimilarityRuleIdUnique] DEFAULT (newid()) ROWGUIDCOL NOT NULL,
    [Entity]                          NVARCHAR (100)   NULL,
    [AzureServiceConnectionId]        UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK_AdvancedSimilarityRuleBase] PRIMARY KEY CLUSTERED ([AdvancedSimilarityRuleId] ASC) WITH (FILLFACTOR = 80)
);

