CREATE TABLE [dbo].[OrganizationBase] (
    [OrganizationId]                                    UNIQUEIDENTIFIER NOT NULL,
    [Name]                                              NVARCHAR (160)   NOT NULL,
    [UserGroupId]                                       UNIQUEIDENTIFIER NULL,
    [PrivilegeUserGroupId]                              UNIQUEIDENTIFIER NULL,
    [FiscalPeriodType]                                  INT              CONSTRAINT [DF_OrganizationBase_FiscalPeriodType] DEFAULT ((2002)) NOT NULL,
    [FiscalCalendarStart]                               DATETIME         NULL,
    [DateFormatCode]                                    INT              CONSTRAINT [Set_To_Zero125] DEFAULT ((0)) NOT NULL,
    [TimeFormatCode]                                    INT              CONSTRAINT [Set_To_Zero126] DEFAULT ((0)) NOT NULL,
    [CurrencySymbol]                                    NVARCHAR (13)    CONSTRAINT [DF_OrganizationBase_CurrencySymbol] DEFAULT ('$') NULL,
    [WeekStartDayCode]                                  INT              CONSTRAINT [Set_To_Zero127] DEFAULT ((0)) NOT NULL,
    [DateSeparator]                                     NVARCHAR (5)     CONSTRAINT [ORG_DATE_SEPARATOR2] DEFAULT ('/') NULL,
    [FullNameConventionCode]                            INT              CONSTRAINT [Set_To_Zero128] DEFAULT ((0)) NOT NULL,
    [NegativeFormatCode]                                INT              CONSTRAINT [Set_To_Zero129] DEFAULT ((0)) NOT NULL,
    [NumberFormat]                                      NVARCHAR (2)     CONSTRAINT [ORG_NUMBER_FORMAT2] DEFAULT ('us') NULL,
    [IsDisabled]                                        BIT              CONSTRAINT [Set_To_Zero130] DEFAULT ((0)) NULL,
    [DisabledReason]                                    NVARCHAR (500)   NULL,
    [KbPrefix]                                          NVARCHAR (20)    CONSTRAINT [DF_OrganizationBase_KbPrefix] DEFAULT ('KBA') NULL,
    [CurrentKbNumber]                                   INT              CONSTRAINT [ORG_LOWER_BOUND_10007] DEFAULT ((1000)) NULL,
    [CasePrefix]                                        NVARCHAR (20)    CONSTRAINT [DF_OrganizationBase_CasePrefix] DEFAULT ('CAS') NULL,
    [CurrentCaseNumber]                                 INT              CONSTRAINT [ORG_LOWER_BOUND_10008] DEFAULT ((1000)) NULL,
    [ContractPrefix]                                    NVARCHAR (20)    CONSTRAINT [DF_OrganizationBase_ContractPrefix] DEFAULT ('CNR') NULL,
    [CurrentContractNumber]                             INT              CONSTRAINT [ORG_LOWER_BOUND_10009] DEFAULT ((1000)) NULL,
    [QuotePrefix]                                       NVARCHAR (20)    CONSTRAINT [DF_OrganizationBase_QuotePrefix] DEFAULT ('QUO') NULL,
    [CurrentQuoteNumber]                                INT              CONSTRAINT [ORG_LOWER_BOUND_100010] DEFAULT ((1000)) NULL,
    [OrderPrefix]                                       NVARCHAR (20)    CONSTRAINT [DF_OrganizationBase_OrderPrefix] DEFAULT ('ORD') NULL,
    [CurrentOrderNumber]                                INT              CONSTRAINT [ORG_LOWER_BOUND_100011] DEFAULT ((1000)) NULL,
    [InvoicePrefix]                                     NVARCHAR (20)    CONSTRAINT [DF_OrganizationBase_InvoicePrefix] DEFAULT ('INV') NULL,
    [CurrentInvoiceNumber]                              INT              CONSTRAINT [ORG_LOWER_BOUND_100012] DEFAULT ((1000)) NULL,
    [UniqueSpecifierLength]                             INT              CONSTRAINT [Unique_Specifier_Length2] DEFAULT ((6)) NULL,
    [CreatedOn]                                         DATETIME         NULL,
    [ModifiedOn]                                        DATETIME         NULL,
    [FiscalYearFormat]                                  NVARCHAR (25)    NULL,
    [FiscalPeriodFormat]                                NVARCHAR (25)    NULL,
    [FiscalYearPeriodConnect]                           NVARCHAR (5)     CONSTRAINT [DF_OrganizationBase_FiscalYearPeriodConnect] DEFAULT ('s') NOT NULL,
    [LanguageCode]                                      INT              NULL,
    [SortId]                                            INT              NULL,
    [DateFormatString]                                  NVARCHAR (255)   NULL,
    [TimeFormatString]                                  NVARCHAR (255)   NULL,
    [PricingDecimalPrecision]                           INT              CONSTRAINT [DF_OrganizationBase_PricingDecimalPrecision] DEFAULT ((2)) NOT NULL,
    [ShowWeekNumber]                                    BIT              CONSTRAINT [Set_To_Zero131] DEFAULT ((0)) NULL,
    [NextTrackingNumber]                                INT              NULL,
    [TagMaxAggressiveCycles]                            TINYINT          CONSTRAINT [DF_OrganizationBase_TagMaxAggressiveCycles] DEFAULT ((2)) NOT NULL,
    [TokenKey]                                          NVARCHAR (90)    NULL,
    [SystemUserId]                                      UNIQUEIDENTIFIER NULL,
    [CreatedBy]                                         UNIQUEIDENTIFIER NULL,
    [GrantAccessToNetworkService]                       BIT              CONSTRAINT [DF_OrganizationBase_GrantAccessToNetworkService] DEFAULT ((0)) NULL,
    [AllowOutlookScheduledSyncs]                        BIT              CONSTRAINT [DF_OrganizationBase_AllowOutlookScheduledSyncs] DEFAULT ((1)) NOT NULL,
    [AllowMarketingEmailExecution]                      BIT              CONSTRAINT [DF_OrganizationBase_AllowMarketingEmailExecution] DEFAULT ((1)) NOT NULL,
    [SqlAccessGroupId]                                  UNIQUEIDENTIFIER NULL,
    [CurrencyFormatCode]                                INT              CONSTRAINT [DF_OrganizationBase_CurrencyFormatCode] DEFAULT ((0)) NOT NULL,
    [FiscalSettingsUpdated]                             BIT              CONSTRAINT [DF_OrganizationBase_FiscalSettingsUpdated] DEFAULT ((0)) NOT NULL,
    [ReportingGroupId]                                  UNIQUEIDENTIFIER NULL,
    [TokenExpiry]                                       SMALLINT         NULL,
    [ShareToPreviousOwnerOnAssign]                      BIT              CONSTRAINT [DF_OrganizationBase_ShareToPreviousOwnerOnAssign] DEFAULT ((1)) NOT NULL,
    [AcknowledgementTemplateId]                         UNIQUEIDENTIFIER NULL,
    [ModifiedBy]                                        UNIQUEIDENTIFIER NULL,
    [IntegrationUserId]                                 UNIQUEIDENTIFIER NULL,
    [TrackingTokenIdBase]                               INT              NULL,
    [BusinessClosureCalendarId]                         UNIQUEIDENTIFIER NULL,
    [AllowAutoUnsubscribeAcknowledgement]               BIT              CONSTRAINT [DF_OrganizationBase_AllowAutoUnsubscribeAcknowledgement] DEFAULT ((0)) NULL,
    [AllowAutoUnsubscribe]                              BIT              CONSTRAINT [DF_OrganizationBase_AllowAutoUnsubscribe] DEFAULT ((0)) NULL,
    [Picture]                                           NVARCHAR (MAX)   NULL,
    [VersionNumber]                                     ROWVERSION       NULL,
    [TrackingPrefix]                                    NVARCHAR (256)   NULL,
    [MinOutlookSyncInterval]                            INT              CONSTRAINT [DF_OrganizationBase_MinOutlookSyncInterval] DEFAULT ((900000)) NOT NULL,
    [BulkOperationPrefix]                               NVARCHAR (20)    CONSTRAINT [DF_OrganizationBase_BulkOperationPrefix] DEFAULT ('BO') NOT NULL,
    [AllowAutoResponseCreation]                         BIT              CONSTRAINT [DF_OrganizationBase_AllowAutoResponseCreation] DEFAULT ((1)) NULL,
    [MaximumTrackingNumber]                             INT              NULL,
    [CampaignPrefix]                                    NVARCHAR (20)    CONSTRAINT [DF_OrganizationBase_CampaignPrefix] DEFAULT ('CMP') NOT NULL,
    [SqlAccessGroupName]                                NVARCHAR (256)   NULL,
    [CurrentCampaignNumber]                             INT              CONSTRAINT [DF_OrganizationBase_CurrentCampaignNumber] DEFAULT ((1000)) NULL,
    [FiscalYearDisplayCode]                             TINYINT          CONSTRAINT [DF_OrganizationBase_FiscalYearDisplayCode] DEFAULT ((1)) NOT NULL,
    [SiteMapXml]                                        NVARCHAR (MAX)   NULL,
    [IsRegistered]                                      BIT              CONSTRAINT [DF_OrganizationBase_IsRegistered] DEFAULT ((0)) NULL,
    [ReportingGroupName]                                NVARCHAR (256)   NULL,
    [CurrentBulkOperationNumber]                        INT              CONSTRAINT [DF_OrganizationBase_CurrentBulkOperationNumber] DEFAULT ((1000)) NULL,
    [SchemaNamePrefix]                                  NVARCHAR (8)     CONSTRAINT [DF_OrganizationBase_SchemaNamePrefix] DEFAULT ('new') NULL,
    [IgnoreInternalEmail]                               BIT              CONSTRAINT [DF_OrganizationBase_IgnoreInternalEmail] DEFAULT ((0)) NOT NULL,
    [TagPollingPeriod]                                  INT              CONSTRAINT [DF_OrganizationBase_TagPollingPeriod] DEFAULT ((600000)) NOT NULL,
    [TrackingTokenIdDigits]                             TINYINT          NULL,
    [NumberGroupFormat]                                 NVARCHAR (50)    NULL,
    [LongDateFormatCode]                                INT              CONSTRAINT [DF_OrganizationBase_LongDateFormatCode] DEFAULT ((0)) NOT NULL,
    [UTCConversionTimeZoneCode]                         INT              NULL,
    [TimeZoneRuleVersionNumber]                         INT              NULL,
    [CurrentImportSequenceNumber]                       INT              CONSTRAINT [DF_OrganizationBase_CurrentImportSequenceNumber] DEFAULT ((1)) NOT NULL,
    [ParsedTablePrefix]                                 NVARCHAR (20)    CONSTRAINT [DF_OrganizationBase_ParsedTablePrefix] DEFAULT ('PIF') NOT NULL,
    [V3CalloutConfigHash]                               NVARCHAR (256)   NULL,
    [IsFiscalPeriodMonthBased]                          BIT              CONSTRAINT [DF_OrganizationBase_IsFiscalPeriodMonthBased] DEFAULT ((0)) NOT NULL,
    [LocaleId]                                          INT              NOT NULL,
    [ParsedTableColumnPrefix]                           NVARCHAR (20)    CONSTRAINT [DF_OrganizationBase_ParsedTableColumnPrefix] DEFAULT ('COL') NOT NULL,
    [SupportUserId]                                     UNIQUEIDENTIFIER NULL,
    [AMDesignator]                                      NVARCHAR (25)    CONSTRAINT [DF_OrganizationBase_AMDesignator] DEFAULT ('AM') NOT NULL,
    [CurrencyDisplayOption]                             INT              CONSTRAINT [DF_OrganizationBase_CurrencyDisplayOption] DEFAULT ((0)) NOT NULL,
    [MinAddressBookSyncInterval]                        INT              CONSTRAINT [DF_OrganizationBase_MinAddressBookSyncInterval] DEFAULT ((3600000)) NOT NULL,
    [IsDuplicateDetectionEnabledForOnlineCreateUpdate]  BIT              CONSTRAINT [DF_OrganizationBase_IsDuplicateDetectionEnabledForOnlineCreateUpdate] DEFAULT ((1)) NOT NULL,
    [FeatureSet]                                        NVARCHAR (MAX)   NULL,
    [BlockedAttachments]                                NVARCHAR (MAX)   NULL,
    [IsDuplicateDetectionEnabledForOfflineSync]         BIT              CONSTRAINT [DF_OrganizationBase_IsDuplicateDetectionEnabledForOfflineSync] DEFAULT ((1)) NOT NULL,
    [AllowOfflineScheduledSyncs]                        BIT              CONSTRAINT [DF_OrganizationBase_AllowOfflineScheduledSyncs] DEFAULT ((1)) NOT NULL,
    [AllowUnresolvedPartiesOnEmailSend]                 BIT              CONSTRAINT [DF_OrganizationBase_AllowUnresolvedPartiesOnEmailSend] DEFAULT ((0)) NOT NULL,
    [TimeSeparator]                                     NVARCHAR (5)     NULL,
    [CurrentParsedTableNumber]                          INT              CONSTRAINT [DF_OrganizationBase_CurrentParsedTableNumber] DEFAULT ((1)) NOT NULL,
    [MinOfflineSyncInterval]                            INT              CONSTRAINT [DF_OrganizationBase_MinOfflineSyncInterval] DEFAULT ((900000)) NOT NULL,
    [AllowWebExcelExport]                               BIT              CONSTRAINT [DF_OrganizationBase_AllowWebExcelExport] DEFAULT ((1)) NOT NULL,
    [ReferenceSiteMapXml]                               NVARCHAR (MAX)   NULL,
    [IsDuplicateDetectionEnabledForImport]              BIT              CONSTRAINT [DF_OrganizationBase_IsDuplicateDetectionEnabledForImport] DEFAULT ((1)) NOT NULL,
    [CalendarType]                                      INT              CONSTRAINT [DF_OrganizationBase_CalendarType] DEFAULT ((2)) NULL,
    [SQMEnabled]                                        BIT              CONSTRAINT [DF_OrganizationBase_SQMEnabled] DEFAULT ((0)) NULL,
    [NegativeCurrencyFormatCode]                        INT              CONSTRAINT [DF_OrganizationBase_NegativeCurrencyFormatCode] DEFAULT ((0)) NOT NULL,
    [AllowAddressBookSyncs]                             BIT              CONSTRAINT [DF_OrganizationBase_AllowAddressBookSyncs] DEFAULT ((1)) NOT NULL,
    [ISVIntegrationCode]                                INT              CONSTRAINT [DF_OrganizationBase_ISVIntegrationCode] DEFAULT ((0)) NOT NULL,
    [DecimalSymbol]                                     NVARCHAR (5)     CONSTRAINT [DF_OrganizationBase_DecimalSymbol] DEFAULT ('.') NOT NULL,
    [MaxUploadFileSize]                                 INT              CONSTRAINT [DF_OrganizationBase_MaxUploadFileSize] DEFAULT ((5242880)) NOT NULL,
    [IsAppMode]                                         BIT              CONSTRAINT [DF_OrganizationBase_IsAppMode] DEFAULT ((0)) NOT NULL,
    [EnablePricingOnCreate]                             BIT              CONSTRAINT [DF_OrganizationBase_EnablePricingOnCreate] DEFAULT ((1)) NOT NULL,
    [IsSOPIntegrationEnabled]                           BIT              CONSTRAINT [DF_OrganizationBase_IsSOPIntegrationEnabled] DEFAULT ((0)) NOT NULL,
    [PMDesignator]                                      NVARCHAR (25)    CONSTRAINT [DF_OrganizationBase_PMDesignator] DEFAULT ('PM') NOT NULL,
    [CurrencyDecimalPrecision]                          INT              CONSTRAINT [DF_OrganizationBase_CurrencyDecimalPrecision] DEFAULT ((2)) NOT NULL,
    [MaxAppointmentDurationDays]                        INT              CONSTRAINT [DF_OrganizationBase_MaxAppointmentDurationDays] DEFAULT ((10)) NOT NULL,
    [EmailSendPollingPeriod]                            INT              CONSTRAINT [DF_OrganizationBase_EmailSendPollingPeriod] DEFAULT ((600000)) NOT NULL,
    [RenderSecureIFrameForEmail]                        BIT              CONSTRAINT [DF_OrganizationBase_RenderSecureIFrameForEmail] DEFAULT ((0)) NOT NULL,
    [NumberSeparator]                                   NVARCHAR (5)     CONSTRAINT [DF_OrganizationBase_NumberSeparator] DEFAULT (',') NOT NULL,
    [PrivReportingGroupId]                              UNIQUEIDENTIFIER NULL,
    [BaseCurrencyId]                                    UNIQUEIDENTIFIER NULL,
    [MaxRecordsForExportToExcel]                        INT              CONSTRAINT [DF_OrganizationBase_MaxRecordsForExportToExcel] DEFAULT ((100000)) NOT NULL,
    [PrivReportingGroupName]                            NVARCHAR (256)   NULL,
    [YearStartWeekCode]                                 INT              CONSTRAINT [DF_OrganizationBase_YearStartWeekCode] DEFAULT ((0)) NOT NULL,
    [IsPresenceEnabled]                                 BIT              CONSTRAINT [DF_OrganizationBase_IsPresenceEnabled] DEFAULT ((1)) NULL,
    [IsDuplicateDetectionEnabled]                       BIT              CONSTRAINT [DF_OrganizationBase_IsDuplicateDetectionEnabled] DEFAULT ((1)) NOT NULL,
    [RecurrenceExpansionJobBatchInterval]               INT              CONSTRAINT [DF_OrganizationBase_RecurrenceExpansionJobBatchInterval] DEFAULT ((0)) NOT NULL,
    [DefaultRecurrenceEndRangeType]                     INT              CONSTRAINT [DF_OrganizationBase_DefaultRecurrenceEndRangeType] DEFAULT ((2)) NULL,
    [HashMinAddressCount]                               INT              NULL,
    [RequireApprovalForUserEmail]                       BIT              CONSTRAINT [DF_OrganizationBase_RequireApprovalForUserEmail] DEFAULT ((1)) NOT NULL,
    [RecurrenceDefaultNumberOfOccurrences]              INT              CONSTRAINT [DF_OrganizationBase_RecurrenceDefaultNumberOfOccurrences] DEFAULT ((10)) NOT NULL,
    [ModifiedOnBehalfBy]                                UNIQUEIDENTIFIER NULL,
    [RequireApprovalForQueueEmail]                      BIT              CONSTRAINT [DF_OrganizationBase_RequireApprovalForQueueEmail] DEFAULT ((1)) NOT NULL,
    [AllowEntityOnlyAudit]                              BIT              CONSTRAINT [DF_OrganizationBase_AllowEntityOnlyAudit] DEFAULT ((1)) NOT NULL,
    [IsAuditEnabled]                                    BIT              CONSTRAINT [DF_OrganizationBase_IsAuditEnabled] DEFAULT ((0)) NOT NULL,
    [RecurrenceExpansionSynchCreateMax]                 INT              CONSTRAINT [DF_OrganizationBase_RecurrenceExpansionSynchCreateMax] DEFAULT ((15)) NOT NULL,
    [GoalRollupExpiryTime]                              INT              CONSTRAINT [DF_OrganizationBase_GoalRollupExpiryTime] DEFAULT ((30)) NOT NULL,
    [BaseCurrencyPrecision]                             INT              CONSTRAINT [DF_OrganizationBase_BaseCurrencyPrecision] DEFAULT ((2)) NOT NULL,
    [FiscalPeriodFormatPeriod]                          INT              CONSTRAINT [DF_OrganizationBase_FiscalPeriodFormatPeriod] DEFAULT ((1)) NULL,
    [AllowClientMessageBarAd]                           BIT              CONSTRAINT [DF_OrganizationBase_AllowClientMessageBarAd] DEFAULT ((1)) NOT NULL,
    [InitialVersion]                                    NVARCHAR (20)    NULL,
    [HashFilterKeywords]                                NVARCHAR (MAX)   NULL,
    [NextCustomObjectTypeCode]                          INT              CONSTRAINT [DF_OrganizationBase_NextCustomObjectTypeCode] DEFAULT ((10000)) NOT NULL,
    [ExpireSubscriptionsInDays]                         INT              CONSTRAINT [DF_OrganizationBase_ExpireSubscriptionsInDays] DEFAULT ((90)) NOT NULL,
    [OrgDbOrgSettings]                                  NVARCHAR (MAX)   NULL,
    [PastExpansionWindow]                               INT              CONSTRAINT [DF_OrganizationBase_PastExpansionWindow] DEFAULT ((3)) NOT NULL,
    [EnableSmartMatching]                               BIT              NULL,
    [MaxRecordsForLookupFilters]                        INT              CONSTRAINT [DF_OrganizationBase_MaxRecordsForLookupFilters] DEFAULT ((300)) NOT NULL,
    [BaseCurrencySymbol]                                NVARCHAR (4000)  CONSTRAINT [DF_OrganizationBase_BaseCurrencySymbol] DEFAULT ('$') NOT NULL,
    [ReportScriptErrors]                                INT              CONSTRAINT [DF_OrganizationBase_ReportScriptErrors] DEFAULT ((0)) NOT NULL,
    [RecurrenceExpansionJobBatchSize]                   INT              CONSTRAINT [DF_OrganizationBase_RecurrenceExpansionJobBatchSize] DEFAULT ((0)) NOT NULL,
    [FutureExpansionWindow]                             INT              CONSTRAINT [DF_OrganizationBase_FutureExpansionWindow] DEFAULT ((12)) NOT NULL,
    [GetStartedPaneContentEnabled]                      BIT              CONSTRAINT [DF_OrganizationBase_GetStartedPaneContentEnabled] DEFAULT ((1)) NOT NULL,
    [SampleDataImportId]                                UNIQUEIDENTIFIER NULL,
    [BaseISOCurrencyCode]                               NVARCHAR (4000)  CONSTRAINT [DF_OrganizationBase_BaseISOCurrencyCode] DEFAULT ('USD') NOT NULL,
    [GoalRollupFrequency]                               INT              CONSTRAINT [DF_OrganizationBase_GoalRollupFrequency] DEFAULT ((24)) NOT NULL,
    [CreatedOnBehalfBy]                                 UNIQUEIDENTIFIER NULL,
    [HashDeltaSubjectCount]                             INT              NULL,
    [HashMaxCount]                                      INT              NULL,
    [FiscalYearFormatYear]                              INT              CONSTRAINT [DF_OrganizationBase_FiscalYearFormatYear] DEFAULT ((1)) NULL,
    [FiscalYearFormatPrefix]                            INT              CONSTRAINT [DF_OrganizationBase_FiscalYearFormatPrefix] DEFAULT ((1)) NULL,
    [PinpointLanguageCode]                              INT              NULL,
    [FiscalYearFormatSuffix]                            INT              CONSTRAINT [DF_OrganizationBase_FiscalYearFormatSuffix] DEFAULT ((3)) NULL,
    [AllowUserFormModePreference]                       BIT              CONSTRAINT [DF_OrganizationBase_AllowUserFormModePreference] DEFAULT ((1)) NOT NULL,
    [MaximumActiveBusinessProcessFlowsAllowedPerEntity] INT              CONSTRAINT [DF_OrganizationBase_MaximumActiveBusinessProcessFlowsAllowedPerEntity] DEFAULT ((10)) NULL,
    [YammerGroupId]                                     INT              NULL,
    [IsUserAccessAuditEnabled]                          BIT              CONSTRAINT [DF_OrganizationBase_IsUserAccessAuditEnabled] DEFAULT ((0)) NOT NULL,
    [IsDefaultCountryCodeCheckEnabled]                  BIT              CONSTRAINT [DF_OrganizationBase_IsDefaultCountryCodeCheckEnabled] DEFAULT ((1)) NOT NULL,
    [MetadataSyncLastTimeOfNeverExpiredDeletedObjects]  DATETIME         NULL,
    [IncomingEmailExchangeEmailRetrievalBatchSize]      INT              CONSTRAINT [DF_OrganizationBase_IncomingEmailExchangeEmailRetrievalBatchSize] DEFAULT ((10)) NULL,
    [QuickFindRecordLimitEnabled]                       BIT              CONSTRAINT [DF_OrganizationBase_QuickFindRecordLimitEnabled] DEFAULT ((1)) NOT NULL,
    [YammerOAuthAccessTokenExpired]                     BIT              NULL,
    [UseSkypeProtocol]                                  BIT              CONSTRAINT [DF_OrganizationBase_UseSkypeProtocol] DEFAULT ((1)) NOT NULL,
    [DefaultEmailServerProfileId]                       UNIQUEIDENTIFIER NULL,
    [GenerateAlertsForErrors]                           BIT              CONSTRAINT [DF_OrganizationBase_GenerateAlertsForErrors] DEFAULT ((1)) NOT NULL,
    [DefaultCountryCode]                                NVARCHAR (15)    NULL,
    [EmailCorrelationEnabled]                           BIT              CONSTRAINT [DF_OrganizationBase_EmailCorrelationEnabled] DEFAULT ((1)) NOT NULL,
    [UserAccessAuditingInterval]                        INT              CONSTRAINT [DF_OrganizationBase_UserAccessAuditingInterval] DEFAULT ((4)) NOT NULL,
    [IsAutoSaveEnabled]                                 BIT              CONSTRAINT [DF_OrganizationBase_IsAutoSaveEnabled] DEFAULT ((1)) NOT NULL,
    [DefaultEmailSettings]                              NVARCHAR (MAX)   NULL,
    [MetadataSyncTimestamp]                             BIGINT           CONSTRAINT [DF_OrganizationBase_MetadataSyncTimestamp] DEFAULT ((1)) NOT NULL,
    [YammerNetworkPermalink]                            NVARCHAR (256)   NULL,
    [EmailConnectionChannel]                            INT              CONSTRAINT [DF_OrganizationBase_EmailConnectionChannel] DEFAULT ((0)) NOT NULL,
    [EntityImageId]                                     UNIQUEIDENTIFIER NULL,
    [NotifyMailboxOwnerOfEmailServerLevelAlerts]        BIT              CONSTRAINT [DF_OrganizationBase_NotifyMailboxOwnerOfEmailServerLevelAlerts] DEFAULT ((0)) NOT NULL,
    [BingMapsApiKey]                                    NVARCHAR (1024)  NULL,
    [GenerateAlertsForInformation]                      BIT              CONSTRAINT [DF_OrganizationBase_GenerateAlertsForInformation] DEFAULT ((1)) NOT NULL,
    [GenerateAlertsForWarnings]                         BIT              CONSTRAINT [DF_OrganizationBase_GenerateAlertsForWarnings] DEFAULT ((0)) NOT NULL,
    [YammerPostMethod]                                  INT              NULL,
    [AllowUsersSeeAppdownloadMessage]                   BIT              CONSTRAINT [DF_OrganizationBase_AllowUsersSeeAppdownloadMessage] DEFAULT ((1)) NOT NULL,
    [UseReadForm]                                       BIT              CONSTRAINT [DF_OrganizationBase_UseReadForm] DEFAULT ((0)) NOT NULL,
    [EnableBingMapsIntegration]                         BIT              CONSTRAINT [DF_OrganizationBase_EnableBingMapsIntegration] DEFAULT ((1)) NOT NULL,
    [DisableSocialCare]                                 BIT              CONSTRAINT [DF_OrganizationBase_DisableSocialCare] DEFAULT ((0)) NOT NULL,
    [SocialInsightsInstance]                            NVARCHAR (MAX)   NULL,
    [UseInbuiltRuleForDefaultPricelistSelection]        BIT              CONSTRAINT [DF_OrganizationBase_UseInbuiltRuleForDefaultPricelistSelection] DEFAULT ((1)) NULL,
    [DiscountCalculationMethod]                         INT              CONSTRAINT [DF_OrganizationBase_DiscountCalculationMethod] DEFAULT ((0)) NOT NULL,
    [IsAssignedTasksSyncEnabled]                        BIT              CONSTRAINT [DF_OrganizationBase_IsAssignedTasksSyncEnabled] DEFAULT ((0)) NOT NULL,
    [IsAppointmentAttachmentSyncEnabled]                BIT              CONSTRAINT [DF_OrganizationBase_IsAppointmentAttachmentSyncEnabled] DEFAULT ((0)) NOT NULL,
    [IsContactMailingAddressSyncEnabled]                BIT              CONSTRAINT [DF_OrganizationBase_IsContactMailingAddressSyncEnabled] DEFAULT ((1)) NOT NULL,
    [MaxSupportedInternetExplorerVersion]               INT              CONSTRAINT [DF_OrganizationBase_MaxSupportedInternetExplorerVersion] DEFAULT ((10)) NOT NULL,
    [CreateProductsWithoutParentInActiveState]          BIT              CONSTRAINT [DF_OrganizationBase_CreateProductsWithoutParentInActiveState] DEFAULT ((0)) NOT NULL,
    [SlaPauseStates]                                    NVARCHAR (MAX)   NULL,
    [MaxProductsInBundle]                               INT              CONSTRAINT [DF_OrganizationBase_MaxProductsInBundle] DEFAULT ((15)) NOT NULL,
    [OOBPriceCalculationEnabled]                        BIT              CONSTRAINT [DF_OrganizationBase_OOBPriceCalculationEnabled] DEFAULT ((1)) NOT NULL,
    [CascadeStatusUpdate]                               BIT              CONSTRAINT [DF_OrganizationBase_CascadeStatusUpdate] DEFAULT ((0)) NULL,
    [RestrictStatusUpdate]                              BIT              CONSTRAINT [DF_OrganizationBase_RestrictStatusUpdate] DEFAULT ((0)) NULL,
    [MaxDepthForHierarchicalSecurityModel]              INT              CONSTRAINT [DF_OrganizationBase_MaxDepthForHierarchicalSecurityModel] DEFAULT ((3)) NOT NULL,
    [IsHierarchicalSecurityModelEnabled]                BIT              CONSTRAINT [DF_OrganizationBase_IsHierarchicalSecurityModelEnabled] DEFAULT ((0)) NOT NULL,
    [GlobalHelpUrlEnabled]                              BIT              CONSTRAINT [DF_OrganizationBase_GlobalHelpUrlEnabled] DEFAULT ((0)) NOT NULL,
    [DisplayNavigationTour]                             BIT              CONSTRAINT [DF_OrganizationBase_DisplayNavigationTour] DEFAULT ((1)) NOT NULL,
    [GlobalAppendUrlParametersEnabled]                  BIT              CONSTRAINT [DF_OrganizationBase_GlobalAppendUrlParametersEnabled] DEFAULT ((0)) NOT NULL,
    [SocialInsightsTermsAccepted]                       BIT              CONSTRAINT [DF_OrganizationBase_SocialInsightsTermsAccepted] DEFAULT ((0)) NULL,
    [SocialInsightsEnabled]                             BIT              CONSTRAINT [DF_OrganizationBase_SocialInsightsEnabled] DEFAULT ((0)) NULL,
    [GlobalHelpUrl]                                     NVARCHAR (500)   NULL,
    [SignupOutlookDownloadFWLink]                       NVARCHAR (200)   CONSTRAINT [DF_OrganizationBase_SignupOutlookDownloadFWLink] DEFAULT ('') NOT NULL,
    [MaximumDynamicPropertiesAllowed]                   INT              CONSTRAINT [DF_OrganizationBase_MaximumDynamicPropertiesAllowed] DEFAULT ((50)) NOT NULL,
    [UsePositionHierarchy]                              BIT              CONSTRAINT [DF_OrganizationBase_UsePositionHierarchy] DEFAULT ((0)) NOT NULL,
    [SuppressSLA]                                       BIT              CONSTRAINT [DF_OrganizationBase_SuppressSLA] DEFAULT ((0)) NOT NULL,
    [IsMailboxInactiveBackoffEnabled]                   BIT              CONSTRAINT [DF_OrganizationBase_IsMailboxInactiveBackoffEnabled] DEFAULT ((0)) NOT NULL,
    [MobileOfflineSyncInterval]                         INT              CONSTRAINT [DF_OrganizationBase_MobileOfflineSyncInterval] DEFAULT ((600000)) NOT NULL,
    [PluginTraceLogSetting]                             INT              CONSTRAINT [DF_OrganizationBase_PluginTraceLogSetting] DEFAULT ((0)) NOT NULL,
    [DaysSinceRecordLastModifiedMaxValue]               INT              CONSTRAINT [DF_OrganizationBase_DaysSinceRecordLastModifiedMaxValue] DEFAULT ((9999)) NOT NULL,
    [MaxFolderBasedTrackingMappings]                    INT              CONSTRAINT [DF_OrganizationBase_MaxFolderBasedTrackingMappings] DEFAULT ((25)) NOT NULL,
    [KaPrefix]                                          NVARCHAR (20)    CONSTRAINT [DF_OrganizationBase_KaPrefix] DEFAULT ('KA') NOT NULL,
    [SharePointDeploymentType]                          INT              CONSTRAINT [DF_OrganizationBase_SharePointDeploymentType] DEFAULT ((0)) NULL,
    [TaskBasedFlowEnabled]                              BIT              CONSTRAINT [DF_OrganizationBase_TaskBasedFlowEnabled] DEFAULT ((0)) NOT NULL,
    [MailboxPermanentIssueMinRange]                     INT              CONSTRAINT [DF_OrganizationBase_MailboxPermanentIssueMinRange] DEFAULT ((7)) NOT NULL,
    [IsOneDriveEnabled]                                 BIT              CONSTRAINT [DF_OrganizationBase_IsOneDriveEnabled] DEFAULT ((0)) NOT NULL,
    [MaxVerboseLoggingSyncCycles]                       INT              CONSTRAINT [DF_OrganizationBase_MaxVerboseLoggingSyncCycles] DEFAULT ((9)) NOT NULL,
    [OfficeGraphDelveUrl]                               NVARCHAR (1000)  NULL,
    [WebResourceHash]                                   NVARCHAR (512)   CONSTRAINT [DF_OrganizationBase_WebResourceHash] DEFAULT ('0') NOT NULL,
    [MaxVerboseLoggingMailbox]                          INT              CONSTRAINT [DF_OrganizationBase_MaxVerboseLoggingMailbox] DEFAULT ((5)) NOT NULL,
    [IsFullTextSearchEnabled]                           BIT              CONSTRAINT [DF_OrganizationBase_IsFullTextSearchEnabled] DEFAULT ((0)) NOT NULL,
    [DefaultMobileOfflineProfileId]                     UNIQUEIDENTIFIER NULL,
    [AutoApplyDefaultonCaseCreate]                      BIT              CONSTRAINT [DF_OrganizationBase_AutoApplyDefaultonCaseCreate] DEFAULT ((1)) NOT NULL,
    [IsDelegateAccessEnabled]                           BIT              CONSTRAINT [DF_OrganizationBase_IsDelegateAccessEnabled] DEFAULT ((0)) NOT NULL,
    [KMSettings]                                        NVARCHAR (MAX)   NULL,
    [MobileOfflineMinLicenseTrial]                      INT              CONSTRAINT [DF_OrganizationBase_MobileOfflineMinLicenseTrial] DEFAULT ((0)) NOT NULL,
    [DefaultThemeData]                                  NVARCHAR (MAX)   NULL,
    [AutoApplySLA]                                      BIT              CONSTRAINT [DF_OrganizationBase_AutoApplySLA] DEFAULT ((0)) NOT NULL,
    [MailboxIntermittentIssueMinRange]                  INT              CONSTRAINT [DF_OrganizationBase_MailboxIntermittentIssueMinRange] DEFAULT ((2)) NOT NULL,
    [HighContrastThemeData]                             NVARCHAR (MAX)   NULL,
    [IsFolderBasedTrackingEnabled]                      BIT              CONSTRAINT [DF_OrganizationBase_IsFolderBasedTrackingEnabled] DEFAULT ((0)) NOT NULL,
    [PrivacyStatementUrl]                               NVARCHAR (500)   NULL,
    [MobileOfflineMinLicenseProd]                       INT              CONSTRAINT [DF_OrganizationBase_MobileOfflineMinLicenseProd] DEFAULT ((30)) NOT NULL,
    [ExpireChangeTrackingInDays]                        INT              CONSTRAINT [DF_OrganizationBase_ExpireChangeTrackingInDays] DEFAULT ((30)) NOT NULL,
    [ExternalPartyCorrelationKeys]                      NVARCHAR (MAX)   NULL,
    [ShowKBArticleDeprecationNotification]              BIT              CONSTRAINT [DF_OrganizationBase_ShowKBArticleDeprecationNotification] DEFAULT ((1)) NOT NULL,
    [IsMailboxForcedUnlockingEnabled]                   BIT              CONSTRAINT [DF_OrganizationBase_IsMailboxForcedUnlockingEnabled] DEFAULT ((1)) NOT NULL,
    [ExternalPartyEntitySettings]                       NVARCHAR (MAX)   NULL,
    [IsOfficeGraphEnabled]                              BIT              CONSTRAINT [DF_OrganizationBase_IsOfficeGraphEnabled] DEFAULT ((0)) NOT NULL,
    [IsExternalSearchIndexEnabled]                      BIT              CONSTRAINT [DF_OrganizationBase_IsExternalSearchIndexEnabled] DEFAULT ((0)) NOT NULL,
    [CurrentKaNumber]                                   INT              CONSTRAINT [DF_OrganizationBase_CurrentKaNumber] DEFAULT ((1000)) NOT NULL,
    [DelegatedAdminUserId]                              UNIQUEIDENTIFIER NULL,
    [EnforceReadOnlyPlugins]                            BIT              CONSTRAINT [DF_OrganizationBase_EnforceReadOnlyPlugins] DEFAULT ((0)) NOT NULL,
    [IsEmailServerProfileContentFilteringEnabled]       BIT              CONSTRAINT [DF_OrganizationBase_IsEmailServerProfileContentFilteringEnabled] DEFAULT ((1)) NOT NULL,
    [UseLegacyRendering]                                BIT              CONSTRAINT [DF_OrganizationBase_UseLegacyRendering] DEFAULT ((0)) NOT NULL,
    [IsMobileOfflineEnabled]                            BIT              CONSTRAINT [DF_OrganizationBase_IsMobileOfflineEnabled] DEFAULT ((0)) NOT NULL,
    [AzureSchedulerJobCollectionName]                   NVARCHAR (100)   NULL,
    [AutoApplyDefaultonCaseUpdate]                      BIT              CONSTRAINT [DF_OrganizationBase_AutoApplyDefaultonCaseUpdate] DEFAULT ((1)) NOT NULL,
    [IsEnabledForAllRoles]                              BIT              CONSTRAINT [DF_OrganizationBase_IsEnabledForAllRoles] DEFAULT ((1)) NOT NULL,
    [IsPreviewForEmailMonitoringAllowed]                BIT              CONSTRAINT [DF_OrganizationBase_IsPreviewForEmailMonitoringAllowed] DEFAULT ((0)) NOT NULL,
    [IsPreviewForAutoCaptureEnabled]                    BIT              CONSTRAINT [DF_OrganizationBase_IsPreviewForAutoCaptureEnabled] DEFAULT ((0)) NOT NULL,
    [IsResourceBookingExchangeSyncEnabled]              BIT              CONSTRAINT [DF_OrganizationBase_IsResourceBookingExchangeSyncEnabled] DEFAULT ((0)) NOT NULL,
    [PostMessageWhitelistDomains]                       NVARCHAR (500)   NULL,
    [ExternalBaseUrl]                                   NVARCHAR (500)   NULL,
    [MaximumEntitiesWithActiveSLA]                      INT              CONSTRAINT [DF_OrganizationBase_MaximumEntitiesWithActiveSLA] DEFAULT ((7)) NULL,
    [InactivityTimeoutReminderInMins]                   INT              NULL,
    [CortanaProactiveExperienceEnabled]                 BIT              CONSTRAINT [DF_OrganizationBase_CortanaProactiveExperienceEnabled] DEFAULT ((0)) NOT NULL,
    [WidgetProperties]                                  NVARCHAR (250)   NULL,
    [RiErrorStatus]                                     INT              CONSTRAINT [DF_OrganizationBase_RiErrorStatus] DEFAULT ((1)) NULL,
    [DefaultCrmCustomName]                              NVARCHAR (50)    CONSTRAINT [DF_OrganizationBase_DefaultCrmCustomName] DEFAULT ('Dynamics 365 – custom') NOT NULL,
    [OfficeAppsAutoDeploymentEnabled]                   BIT              CONSTRAINT [DF_OrganizationBase_OfficeAppsAutoDeploymentEnabled] DEFAULT ((0)) NOT NULL,
    [InactivityTimeoutInMins]                           INT              NULL,
    [AppDesignerExperienceEnabled]                      BIT              CONSTRAINT [DF_OrganizationBase_AppDesignerExperienceEnabled] DEFAULT ((0)) NOT NULL,
    [ProductRecommendationsEnabled]                     BIT              CONSTRAINT [DF_OrganizationBase_ProductRecommendationsEnabled] DEFAULT ((0)) NOT NULL,
    [PowerBiFeatureEnabled]                             BIT              CONSTRAINT [DF_OrganizationBase_PowerBiFeatureEnabled] DEFAULT ((0)) NOT NULL,
    [EnableMicrosoftFlowIntegration]                    BIT              CONSTRAINT [DF_OrganizationBase_EnableMicrosoftFlowIntegration] DEFAULT ((1)) NOT NULL,
    [UnresolveEmailAddressIfMultipleMatch]              BIT              CONSTRAINT [DF_OrganizationBase_UnresolveEmailAddressIfMultipleMatch] DEFAULT ((0)) NOT NULL,
    [IsReadAuditEnabled]                                BIT              CONSTRAINT [DF_OrganizationBase_IsReadAuditEnabled] DEFAULT ((0)) NOT NULL,
    [CurrentCategoryNumber]                             INT              CONSTRAINT [DF_OrganizationBase_CurrentCategoryNumber] DEFAULT ((1000)) NOT NULL,
    [IsDelveActionHubIntegrationEnabled]                BIT              CONSTRAINT [DF_OrganizationBase_IsDelveActionHubIntegrationEnabled] DEFAULT ((0)) NULL,
    [CategoryPrefix]                                    NVARCHAR (20)    CONSTRAINT [DF_OrganizationBase_CategoryPrefix] DEFAULT ('CAT') NOT NULL,
    [SessionTimeoutInMins]                              INT              NULL,
    [IsActionCardEnabled]                               BIT              CONSTRAINT [DF_OrganizationBase_IsActionCardEnabled] DEFAULT ((0)) NOT NULL,
    [IsActivityAnalysisEnabled]                         BIT              CONSTRAINT [DF_OrganizationBase_IsActivityAnalysisEnabled] DEFAULT ((0)) NULL,
    [IsFolderAutoCreatedonSP]                           BIT              CONSTRAINT [DF_OrganizationBase_IsFolderAutoCreatedonSP] DEFAULT ((0)) NOT NULL,
    [InactivityTimeoutEnabled]                          BIT              CONSTRAINT [DF_OrganizationBase_InactivityTimeoutEnabled] DEFAULT ((0)) NOT NULL,
    [TextAnalyticsEnabled]                              BIT              CONSTRAINT [DF_OrganizationBase_TextAnalyticsEnabled] DEFAULT ((0)) NOT NULL,
    [IsPreviewEnabledForActionCard]                     BIT              CONSTRAINT [DF_OrganizationBase_IsPreviewEnabledForActionCard] DEFAULT ((0)) NOT NULL,
    [IsConflictDetectionEnabledForMobileClient]         BIT              CONSTRAINT [DF_OrganizationBase_IsConflictDetectionEnabledForMobileClient] DEFAULT ((0)) NOT NULL,
    [IsMobileClientOnDemandSyncEnabled]                 BIT              CONSTRAINT [DF_OrganizationBase_IsMobileClientOnDemandSyncEnabled] DEFAULT ((0)) NOT NULL,
    [IsAutoDataCaptureEnabled]                          BIT              CONSTRAINT [DF_OrganizationBase_IsAutoDataCaptureEnabled] DEFAULT ((0)) NOT NULL,
    [MaximumSLAKPIPerEntityWithActiveSLA]               INT              CONSTRAINT [DF_OrganizationBase_MaximumSLAKPIPerEntityWithActiveSLA] DEFAULT ((5)) NULL,
    [MaxConditionsForMobileOfflineFilters]              INT              CONSTRAINT [DF_OrganizationBase_MaxConditionsForMobileOfflineFilters] DEFAULT ((3)) NULL,
    [EnableLPAuthoring]                                 BIT              CONSTRAINT [DF_OrganizationBase_EnableLPAuthoring] DEFAULT ((0)) NOT NULL,
    [OrgInsightsEnabled]                                BIT              CONSTRAINT [DF_OrganizationBase_OrgInsightsEnabled] DEFAULT ((0)) NOT NULL,
    [IsRelationshipInsightsEnabled]                     BIT              CONSTRAINT [DF_OrganizationBase_IsRelationshipInsightsEnabled] DEFAULT ((0)) NULL,
    [ACIWebEndpointUrl]                                 NVARCHAR (500)   NULL,
    [UseLegacyApplicationMetadataSync]                  BIT              CONSTRAINT [DF_OrganizationBase_UseLegacyApplicationMetadataSync] DEFAULT ((1)) NOT NULL,
    [IsEmailMonitoringAllowed]                          BIT              CONSTRAINT [DF_OrganizationBase_IsEmailMonitoringAllowed] DEFAULT ((0)) NOT NULL,
    [SessionTimeoutReminderInMins]                      INT              NULL,
    [ServeStaticResourcesFromAzureCDN]                  BIT              CONSTRAINT [DF_OrganizationBase_ServeStaticResourcesFromAzureCDN] DEFAULT ((1)) NOT NULL,
    [SessionTimeoutEnabled]                             BIT              CONSTRAINT [DF_OrganizationBase_SessionTimeoutEnabled] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [cndx_PrimaryKey_Organization] PRIMARY KEY CLUSTERED ([OrganizationId] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [basecurrency_organization] FOREIGN KEY ([BaseCurrencyId]) REFERENCES [dbo].[TransactionCurrencyBase] ([TransactionCurrencyId]),
    CONSTRAINT [calendar_organization] FOREIGN KEY ([BusinessClosureCalendarId]) REFERENCES [dbo].[CalendarBase] ([CalendarId]),
    CONSTRAINT [DefaultMobileOfflineProfile_Organization] FOREIGN KEY ([DefaultMobileOfflineProfileId]) REFERENCES [dbo].[MobileOfflineProfileBaseIds] ([MobileOfflineProfileId]),
    CONSTRAINT [EmailServerProfile_Organization] FOREIGN KEY ([DefaultEmailServerProfileId]) REFERENCES [dbo].[EmailServerProfileBase] ([EmailServerProfileId]),
    CONSTRAINT [Template_Organization] FOREIGN KEY ([AcknowledgementTemplateId]) REFERENCES [dbo].[TemplateBaseIds] ([TemplateId])
);


GO
EXECUTE sp_tableoption @TableNamePattern = N'[dbo].[OrganizationBase]', @OptionName = N'text in row', @OptionValue = N'7000';


GO
CREATE NONCLUSTERED INDEX [ndx_QF_Name]
    ON [dbo].[OrganizationBase]([Name] ASC) WITH (FILLFACTOR = 80);

