CREATE TABLE [dbo].[RecommendationModelBase] (
    [CreatedOn]                           DATETIME         NULL,
    [ValidUntil]                          DATETIME         NULL,
    [CreatedBy]                           UNIQUEIDENTIFIER NULL,
    [RecommendationModelVersionId]        UNIQUEIDENTIFIER NULL,
    [BasketDataLastSynchronizationStatus] INT              NULL,
    [ProductCatalogCrosssellLinkRating]   DECIMAL (23, 10) CONSTRAINT [DF_RecommendationModelBase_ProductCatalogCrosssellLinkRating] DEFAULT ((0.5)) NOT NULL,
    [OrganizationId]                      UNIQUEIDENTIFIER NOT NULL,
    [CatalogLastSynchronizedOn]           DATETIME         NULL,
    [AzureModelId]                        NVARCHAR (100)   NULL,
    [IsManaged]                           BIT              CONSTRAINT [DF_RecommendationModelBase_IsManaged] DEFAULT ((0)) NOT NULL,
    [ComponentState]                      INT              CONSTRAINT [DF_RecommendationModelBase_ComponentState] DEFAULT ((0)) NOT NULL,
    [BasketDataLastSynchronizedOn]        DATETIME         NULL,
    [ProductCatalogAccessoryLinkRating]   DECIMAL (23, 10) CONSTRAINT [DF_RecommendationModelBase_ProductCatalogAccessoryLinkRating] DEFAULT ((0.5)) NOT NULL,
    [Name]                                NVARCHAR (100)   NULL,
    [AzureServiceConnectionId]            UNIQUEIDENTIFIER NULL,
    [OverwriteTime]                       DATETIME         CONSTRAINT [DF_RecommendationModelBase_OverwriteTime] DEFAULT ((0)) NOT NULL,
    [SolutionId]                          UNIQUEIDENTIFIER CONSTRAINT [DF_RecommendationModelBase_SolutionId] DEFAULT ('fd140aad-4df4-11dd-bd17-0019b9312238') NOT NULL,
    [Description]                         NVARCHAR (MAX)   NULL,
    [CreatedOnBehalfBy]                   UNIQUEIDENTIFIER NULL,
    [RecommendationModelVersionCount]     INT              CONSTRAINT [DF_RecommendationModelBase_RecommendationModelVersionCount] DEFAULT ((0)) NOT NULL,
    [SupportingSolutionId]                UNIQUEIDENTIFIER NULL,
    [RecommendationModelIdUnique]         UNIQUEIDENTIFIER CONSTRAINT [DF_RecommendationModelBase_RecommendationModelIdUnique] DEFAULT (newid()) ROWGUIDCOL NOT NULL,
    [ModifiedBy]                          UNIQUEIDENTIFIER NULL,
    [StateCode]                           INT              NOT NULL,
    [StatusCode]                          INT              NULL,
    [ProductCatalogName]                  NVARCHAR (100)   NULL,
    [MaxRecommendations]                  INT              CONSTRAINT [DF_RecommendationModelBase_MaxRecommendations] DEFAULT ((10)) NOT NULL,
    [MinRecommendationRating]             DECIMAL (23, 10) CONSTRAINT [DF_RecommendationModelBase_MinRecommendationRating] DEFAULT ((0.25)) NOT NULL,
    [RecommendationModelId]               UNIQUEIDENTIFIER NOT NULL,
    [ModifiedOnBehalfBy]                  UNIQUEIDENTIFIER NULL,
    [ModifiedOn]                          DATETIME         NULL,
    [CatalogLastSynchronizationStatus]    INT              NULL,
    [MaximumVersions]                     INT              CONSTRAINT [DF_RecommendationModelBase_MaximumVersions] DEFAULT ((10)) NOT NULL,
    CONSTRAINT [cndx_PrimaryKey_RecommendationModel] PRIMARY KEY CLUSTERED ([RecommendationModelId] ASC) WITH (FILLFACTOR = 80)
);

